// [2026-03-13] 從 ConfigurationService.cs 拆出 ATC NGC 巨集生成（~900 行）
// 所有 NGC 巨集依 AtcType（Turret/Umbrella）動態生成 G-Code 文本
using System;
using System.Collections.Generic;
using System.Text;
using CncController.Models;

namespace CncController.Services
{
    /// <summary>
    /// ATC NGC 巨集生成器 — 依 AtcType 動態生成 m21/m22/m10~m13/m24/m25 等巨集檔案
    /// </summary>
    internal static class AtcNgcGeneratorService
    {
        // ========================================================================================
        // [2026-03-09] 生成 ATC NGC 巨集（依 AtcType 動態生成 4 個類型相關檔案）
        // 回傳 Dictionary<檔名, 內容>：m21.ngc / m22.ngc / toolchange.ngc / m13.ngc
        // ========================================================================================
        internal static Dictionary<string, string> GenerateAtcNgc(MachineConfig config)
        {
            var ngcFiles = new Dictionary<string, string>();

            if (config.Atc.Type == AtcType.None) return ngcFiles;

            // 依 AtcType 選擇 PB Widget 名稱
            string widgetName = config.Atc.Type == AtcType.Umbrella ? "dynatc" : "rackatc";
            int pockets = config.Atc.ToolCount;

            // --- toolchange.ngc（M6 主程式）---
            ngcFiles["toolchange.ngc"] = GenerateToolchangeNgc(config, widgetName, pockets);

            // [2026-03-10] --- m13.ngc（刀庫歸零：Servo→M68 Q0, IO→馬達+Home sensor）---
            ngcFiles["m13.ngc"] = GenerateM13Ngc(config, pockets);

            // [2026-03-09] --- m10.ngc（旋轉到目標刀位，依控制模式分流）---
            if (config.Atc.Type == AtcType.Umbrella)
                ngcFiles["m10.ngc"] = GenerateM10Carousel(config);

            // [2026-03-09] --- m11.ngc / m12.ngc（正轉/反轉一格，依控制模式分流）---
            if (config.Atc.Type == AtcType.Umbrella)
            {
                ngcFiles["m11.ngc"] = GenerateM11Carousel(config);
                ngcFiles["m12.ngc"] = GenerateM12Carousel(config);
            }

            // --- m21.ngc（存刀：spindle → rack/carousel）---
            if (config.Atc.Type == AtcType.Turret)
                ngcFiles["m21.ngc"] = GenerateM21Rack();
            else
                ngcFiles["m21.ngc"] = GenerateM21Carousel();

            // --- m22.ngc（取刀：rack/carousel → spindle）---
            if (config.Atc.Type == AtcType.Turret)
                ngcFiles["m22.ngc"] = GenerateM22Rack();
            else
                ngcFiles["m22.ngc"] = GenerateM22Carousel();

            // [2026-03-09] --- extendatc.ngc / retractatc.ngc（刀盤伸出/收回）---
            if (config.Atc.Type == AtcType.Umbrella)
            {
                ngcFiles["extendatc.ngc"] = GenerateExtendAtcNgc(config);
                ngcFiles["retractatc.ngc"] = GenerateRetractAtcNgc(config);
            }

            // [2026-03-09] --- move_head_above_carousel.ngc / move_tool_to_carousel_height.ngc ---
            if (config.Atc.Type == AtcType.Umbrella)
            {
                ngcFiles["move_head_above_carousel.ngc"] = GenerateMoveHeadAboveCarouselNgc();
                ngcFiles["move_tool_to_carousel_height.ngc"] = GenerateMoveToolToCarouselHeightNgc();
            }

            // [2026-03-10] --- m24.ngc（鬆刀：DO ON → 氣壓推開拉桿）/ m25.ngc（夾刀：DO OFF → 彈簧夾緊）---
            ngcFiles["m24.ngc"] = GenerateM24Ngc(config);
            ngcFiles["m25.ngc"] = GenerateM25Ngc(config);

            // [2026-03-09] --- program_coolant.ngc（換刀後恢復冷卻）---
            ngcFiles["program_coolant.ngc"] = GenerateProgramCoolantNgc();

            return ngcFiles;
        }

        // --- toolchange.ngc ---
        private static string GenerateToolchangeNgc(MachineConfig config, string widgetName, int pockets)
        {
            // [2026-03-09] M6 REMAP 主程式：Rack/Carousel 共用邏輯，僅 Widget 名稱不同
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<toolchange> sub

o100 if [#<_task> EQ 0]
    (DEBUG, Task is null)
    o<toolchange> return [999]
o100 endif

#<number_of_pockets> = {pockets}
o101 if [EXISTS[#<_ini[atc]pockets>]]
    #<number_of_pockets> = #<_ini[atc]pockets>
o101 endif

#<atc_z_tool_change_height> = #3981
#<atc_z_tool_clearance_height> = #3982

#100 = #<selected_tool>
#110 = #<tool_in_spindle>
#120 = #<selected_pocket>
#121 = #<current_pocket>

o110 if [#<selected_tool> EQ #<tool_in_spindle>]
    (PRINT, Requested tool already in spindle)
    o<toolchange> endsub [1]
    M2
o110 endif

#<next_pocket> = 0
#<open_pocket> = 0
#130 = #<number_of_pockets>

o130 do
    o161 if [#[4000 + #130] EQ #<selected_tool>]
        #<next_pocket> = #130
    o161 endif
    o162 if [#[4000 + #130] EQ 0]
        #<open_pocket> = #130
    o162 endif
    #130 = [#130 - 1]
o130 while [#130 GT 0]

o140 if [#<next_pocket> EQ 0]
    (abort, Tool T%d#<selected_tool> not found in rack)
o140 endif

o150 if [#<tool_in_spindle> GT 0]
    o151 if [#<open_pocket> EQ 0]
        (abort, rack is full, cant store tool T#<tool_in_spindle> in rack)
    o151 endif
    o<m21> call [#<open_pocket>]
    (DEBUG, EVAL[vcp.getWidget{{""{widgetName}""}}.store_tool{{#<open_pocket>, #<tool_in_spindle>}}])
    #140 = #<open_pocket>
    #[4000 + #140] = #<tool_in_spindle>
    #3991 = 0
    M61 Q0
    G49
o150 endif

o160 if [#<selected_tool> GT 0]
    o<m22> call [#<next_pocket>]
    (DEBUG, EVAL[vcp.getWidget{{""{widgetName}""}}.store_tool{{#<next_pocket>, 0}}])
    #150 = #<next_pocket>
    #[4000 + #150] = 0
    #3991 = #<selected_tool>
o160 else
    M25
o160 endif

M61 Q#<selected_tool>

o170 if [1 EQ 1]
    G43 H#<selected_tool>
o170 endif

o<program_coolant> call

o<toolchange> endsub [1]

M2
";
        }

        // [2026-03-10] --- m13.ngc（刀庫歸零）---
        // Servo 模式：M68 E0 Q0（轉到 0°）→ 設定 #3990=1（目前刀位=1號位）
        // IO 模式：啟動馬達 → 等 Home sensor → 停止
        private static string GenerateM13Ngc(MachineConfig config, int pockets)
        {
            bool isServo = config.Atc.ControlMode == CarouselControlMode.Servo;

            if (isServo)
            {
                return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(M13: Carousel Reference — Servo Mode)
o<m13> sub

(PRINT, o<m13> Servo Reference Start)

(旋轉刀盤到 0 度 = 1 號刀位)
M68 E0 Q0
G4 P2

(設定目前刀位為 1)
#3990 = 1

(PRINT, o<m13> Servo Reference Complete — Pocket 1)
o<m13> endsub [1]

M2
";
            }
            else
            {
                // IO 模式：正轉馬達 → 等 Home 感測器觸發 → 停止
                int doMotorFwd = config.Atc.DoMotorFwd;
                int diCarouselHome = config.Atc.DiCarouselHome;
                int sensorTimeout = config.Atc.SensorTimeout / 1000;

                var sb = new StringBuilder();
                sb.AppendLine($"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})");
                sb.AppendLine("(M13: Carousel Reference — IO Mode)");
                sb.AppendLine("o<m13> sub");
                sb.AppendLine();
                sb.AppendLine("(PRINT, o<m13> IO Reference Start)");
                sb.AppendLine();
                sb.AppendLine($"M64 P{doMotorFwd}");

                if (!ConfigurationService.IsAtcSimulation)
                {
                    sb.AppendLine($"M66 P{diCarouselHome} L1 Q{sensorTimeout}");
                    sb.AppendLine($"M65 P{doMotorFwd}");
                    sb.AppendLine("o110 if [#5399 EQ -1]");
                    sb.AppendLine("    (PRINT, o<m13> ERROR: Home sensor timeout)");
                    sb.AppendLine("    o<m13> endsub [0]");
                    sb.AppendLine("    M2");
                    sb.AppendLine("o110 endif");
                }
                else
                {
                    sb.AppendLine("G4 P1");
                    sb.AppendLine($"M65 P{doMotorFwd}");
                }

                sb.AppendLine();
                sb.AppendLine("#3990 = 1");
                sb.AppendLine();
                sb.AppendLine("(PRINT, o<m13> IO Reference Complete — Pocket 1)");
                sb.AppendLine("o<m13> endsub [1]");
                sb.AppendLine();
                sb.AppendLine("M2");
                return sb.ToString();
            }
        }

        // --- m21.ngc Rack 版（排刀式存刀）---
        private static string GenerateM21Rack()
        {
            // [2026-03-09] Rack 版：計算 XY 座標 → 移動主軸 → M19 → 滑入刀座 → M24 鬆刀 → Z 退
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<m21> sub

#<target_pocket> = #1

#<rack_id>                = #3979
#<rack_traverse_speed>    = #3980
#<rack_z_load_height>     = #3981
#<rack_safe_z_height>     = #3982
#<rack_pocket_1_x>        = #3983
#<rack_pocket_1_y>        = #3984
#<rack_pocket_2_x>        = #3985
#<rack_pocket_2_y>        = #3986
#<pocket_1_x_clearance>   = #3987
#<pocket_1_y_clearance>   = #3988

#<dx> = [#<rack_pocket_2_x> - #<rack_pocket_1_x>]
#<dy> = [#<rack_pocket_2_y> - #<rack_pocket_1_y>]
#<pocket_index> = [#<target_pocket> - 1]
#<pocket_x> = [#<rack_pocket_1_x> + #<pocket_index> * #<dx>]
#<pocket_y> = [#<rack_pocket_1_y> + #<pocket_index> * #<dy>]

#<clearance_x> = #<pocket_x>
#<clearance_y> = #<pocket_y>
#<store_axis> = 0
#<store_sign> = 1

o100 if [#<rack_id> EQ 1]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<store_axis> = 1
    #<store_sign> = -1
o100 elseif [#<rack_id> EQ 2]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<store_axis> = 1
    #<store_sign> = 1
o100 elseif [#<rack_id> EQ 3]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<store_axis> = 1
    #<store_sign> = -1
o100 elseif [#<rack_id> EQ 4]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<store_axis> = 1
    #<store_sign> = 1
o100 elseif [#<rack_id> EQ 5]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<store_axis> = 2
    #<store_sign> = -1
o100 elseif [#<rack_id> EQ 6]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<store_axis> = 2
    #<store_sign> = 1
o100 elseif [#<rack_id> EQ 7]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<store_axis> = 2
    #<store_sign> = -1
o100 elseif [#<rack_id> EQ 8]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<store_axis> = 2
    #<store_sign> = 1
o100 else
    (PRINT, Error: Invalid rack_id!)
    o<m21> return
o100 endif

G90
G0 G53 Z[#<rack_safe_z_height>]
G0 G53 X[#<clearance_x>] Y[#<clearance_y>]
G1 G53 F[#<rack_traverse_speed>] Z[#<rack_z_load_height>]
M19
G4 P1

o200 if [#<store_axis> EQ 1]
    G1 G53 F[#<rack_traverse_speed>] X[#<pocket_x>]
o200 else
    G1 G53 F[#<rack_traverse_speed>] Y[#<pocket_y>]
o200 endif

M24
G0 G53 Z[#<rack_safe_z_height>]

o<m21> endsub

M2
";
        }

        // --- m21.ngc Carousel 版（斗笠式存刀）---
        private static string GenerateM21Carousel()
        {
            // [2026-03-09] Carousel 版：Z 淨空 → M10 旋轉 → M19 → extendatc → Z 下降 → M24 鬆刀 → Z 退 → retractatc
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<m21> sub

#<target_pocket> = #1

#<atc_z_tool_change_height> = #3981
#<atc_z_tool_clearance_height> = #3982

o100 if [EXISTS[#<_ini[atc]z_tool_change_height>]]
    #<atc_z_tool_change_height> = #<_ini[atc]z_tool_change_height>
o100 endif
o110 if [EXISTS[#<_ini[atc]z_tool_clearance_height>]]
    #<atc_z_tool_clearance_height> = #<_ini[atc]z_tool_clearance_height>
o110 endif

G90
; 1. Move Z to clearance height
G0 G53 Z[#<atc_z_tool_clearance_height>]

; 2. Rotate carousel to target pocket
M10 P[#<target_pocket>]

; 3. Orient spindle
M19
G4 P1

; 4. Extend carousel out
o<extendatc> call

; 5. Lower Z to tool change height
G1 G53 F500 Z[#<atc_z_tool_change_height>]

; 6. Release tool (unclamp drawbar)
M24
G4 P0.5

; 7. Raise Z to clearance height
G0 G53 Z[#<atc_z_tool_clearance_height>]

; 8. Retract carousel
o<retractatc> call

o<m21> endsub

M2
";
        }

        // --- m22.ngc Rack 版（排刀式取刀）---
        private static string GenerateM22Rack()
        {
            // [2026-03-09] Rack 版：移動主軸到 XY → M19 → M24 → Z 下降 → M25 夾刀 → 滑出
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<m22> sub

#<target_pocket> = #1

#<rack_id>                = #3979
#<rack_traverse_speed>    = #3980
#<rack_z_load_height>     = #3981
#<rack_safe_z_height>     = #3982
#<rack_pocket_1_x>        = #3983
#<rack_pocket_1_y>        = #3984
#<rack_pocket_2_x>        = #3985
#<rack_pocket_2_y>        = #3986
#<pocket_1_x_clearance>   = #3987
#<pocket_1_y_clearance>   = #3988

#<dx> = [#<rack_pocket_2_x> - #<rack_pocket_1_x>]
#<dy> = [#<rack_pocket_2_y> - #<rack_pocket_1_y>]
#<pocket_index> = [#<target_pocket> - 1]
#<pocket_x> = [#<rack_pocket_1_x> + #<pocket_index> * #<dx>]
#<pocket_y> = [#<rack_pocket_1_y> + #<pocket_index> * #<dy>]

#<clearance_x> = #<pocket_x>
#<clearance_y> = #<pocket_y>
#<retrieve_axis> = 0
#<retrieve_sign> = 1

o100 if [#<rack_id> EQ 1]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<retrieve_axis> = 1
    #<retrieve_sign> = 1
o100 elseif [#<rack_id> EQ 2]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<retrieve_axis> = 1
    #<retrieve_sign> = -1
o100 elseif [#<rack_id> EQ 3]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<retrieve_axis> = 1
    #<retrieve_sign> = 1
o100 elseif [#<rack_id> EQ 4]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<retrieve_axis> = 1
    #<retrieve_sign> = -1
o100 elseif [#<rack_id> EQ 5]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<retrieve_axis> = 2
    #<retrieve_sign> = 1
o100 elseif [#<rack_id> EQ 6]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<retrieve_axis> = 2
    #<retrieve_sign> = -1
o100 elseif [#<rack_id> EQ 7]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<retrieve_axis> = 2
    #<retrieve_sign> = 1
o100 elseif [#<rack_id> EQ 8]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<retrieve_axis> = 2
    #<retrieve_sign> = -1
o100 else
    (PRINT, Error: Invalid rack_id!)
    o<m22> return
o100 endif

G90
G0 G53 Z[#<rack_safe_z_height>]
G0 G53 X[#<pocket_x>] Y[#<pocket_y>]
M19
M24
G1 G53 F[#<rack_traverse_speed>] Z[#<rack_z_load_height>]
M25

o200 if [#<retrieve_axis> EQ 1]
    G1 G53 F[#<rack_traverse_speed>] X[#<clearance_x>]
o200 else
    G1 G53 F[#<rack_traverse_speed>] Y[#<clearance_y>]
o200 endif

G0 G53 Z[#<rack_safe_z_height>]

o<m22> endsub

M2
";
        }

        // --- m22.ngc Carousel 版（斗笠式取刀）---
        private static string GenerateM22Carousel()
        {
            // [2026-03-09] Carousel 版：Z 淨空 → M10 旋轉 → M19 → extendatc → M24 鬆夾 → Z 下降 → M25 夾刀 → Z 退 → retractatc
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<m22> sub

#<target_pocket> = #1

#<atc_z_tool_change_height> = #3981
#<atc_z_tool_clearance_height> = #3982

o100 if [EXISTS[#<_ini[atc]z_tool_change_height>]]
    #<atc_z_tool_change_height> = #<_ini[atc]z_tool_change_height>
o100 endif
o110 if [EXISTS[#<_ini[atc]z_tool_clearance_height>]]
    #<atc_z_tool_clearance_height> = #<_ini[atc]z_tool_clearance_height>
o110 endif

G90
; 1. Move Z to clearance height
G0 G53 Z[#<atc_z_tool_clearance_height>]

; 2. Rotate carousel to target pocket
M10 P[#<target_pocket>]

; 3. Orient spindle
M19
G4 P1

; 4. Extend carousel out
o<extendatc> call

; 5. Unclamp drawbar to receive tool
M24

; 6. Lower Z to tool change height
G1 G53 F500 Z[#<atc_z_tool_change_height>]

; 7. Clamp tool in spindle
M25
G4 P0.5

; 8. Raise Z to clearance height
G0 G53 Z[#<atc_z_tool_clearance_height>]

; 9. Retract carousel
o<retractatc> call

o<m22> endsub

M2
";
        }

        // [2026-03-09] --- m10.ngc Carousel 版（旋轉到目標刀位，依控制模式分流）---
        private static string GenerateM10Carousel(MachineConfig config)
        {
            bool isServo = config.Atc.ControlMode == CarouselControlMode.Servo;
            int pockets = config.Atc.ToolCount;
            int doMotorFwd = config.Atc.DoMotorFwd;
            int doMotorRev = config.Atc.DoMotorRev;
            int diRotationIndex = config.Atc.DiRotationIndex;
            int sensorTimeout = config.Atc.SensorTimeout / 1000; // ms → s

            if (isServo)
            {
                // [2026-03-10] Servo 模式：讀取當前 analog-out-00，計算最短路徑旋轉
                return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(M10 — Rotate carousel to pocket P, SERVO mode — shortest path)
o<m10> sub

#<target_pocket> = #<p>
#<pockets> = {pockets}
o100 if [EXISTS[#<_ini[atc]pockets>]]
    #<pockets> = #<_ini[atc]pockets>
o100 endif

; 目標角度 (0~360)
#<target_base> = [[#<target_pocket> - 1] * [360.0 / #<pockets>]]
; 當前命令角度（M68 E0 最後送出的值）
#<current> = #<_hal[motion.analog-out-00]>
#<current_base> = [[#<current> + 36000] MOD 360.0]
; 差值 → 正規化到 -180~+180（最短路徑）
#<diff> = [#<target_base> - #<current_base>]
o110 if [#<diff> GT 180]
    #<diff> = [#<diff> - 360]
o110 endif
o120 if [#<diff> LT -180]
    #<diff> = [#<diff> + 360]
o120 endif
#<new_angle> = [#<current> + #<diff>]
#3990 = #<target_pocket>

(PRINT, M10 SERVO: pocket #<target_pocket> current #<current> diff #<diff> new #<new_angle>)
M68 E0 Q[#<new_angle>]
G4 P0.5

o<m10> endsub [1]

M2
";
            }
            else
            {
                // IO 模式：馬達正轉 + RotationIndex 計數到位
                return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(M10 — Rotate carousel to pocket P, IO mode)
o<m10> sub

#<target_pocket> = #<p>
#<pockets> = {pockets}
o100 if [EXISTS[#<_ini[atc]pockets>]]
    #<pockets> = #<_ini[atc]pockets>
o100 endif

#<current_pocket> = #3990
o110 if [#<current_pocket> EQ #<target_pocket>]
    (PRINT, M10 IO: already at pocket #<target_pocket>)
    o<m10> endsub [1]
    M2
o110 endif

; Calculate shortest rotation direction
#<fwd_steps> = [[#<target_pocket> - #<current_pocket> + #<pockets>] MOD #<pockets>]
#<rev_steps> = [[#<current_pocket> - #<target_pocket> + #<pockets>] MOD #<pockets>]

o120 if [#<fwd_steps> LE #<rev_steps>]
    ; Forward rotation
    #<steps> = #<fwd_steps>
    #<count> = 0
    o130 while [#<count> LT #<steps>]
        M64 P{doMotorFwd}
        M66 P{diRotationIndex} L1 Q{sensorTimeout}
        o131 if [#5399 EQ -1]
            M65 P{doMotorFwd}
            (abort, Failed to get rotation index - FWD timeout)
        o131 endif
        M65 P{doMotorFwd}
        G4 P0.1
        #<count> = [#<count> + 1]
    o130 endwhile
o120 else
    ; Reverse rotation
    #<steps> = #<rev_steps>
    #<count> = 0
    o140 while [#<count> LT #<steps>]
        M64 P{doMotorRev}
        M66 P{diRotationIndex} L1 Q{sensorTimeout}
        o141 if [#5399 EQ -1]
            M65 P{doMotorRev}
            (abort, Failed to get rotation index - REV timeout)
        o141 endif
        M65 P{doMotorRev}
        G4 P0.1
        #<count> = [#<count> + 1]
    o140 endwhile
o120 endif

#3990 = #<target_pocket>
(PRINT, M10 IO: arrived at pocket #<target_pocket>)

o<m10> endsub [1]

M2
";
            }
        }

        // [2026-03-09] --- m11.ngc Carousel 版（正轉一格）---
        private static string GenerateM11Carousel(MachineConfig config)
        {
            bool isServo = config.Atc.ControlMode == CarouselControlMode.Servo;
            int pockets = config.Atc.ToolCount;

            if (isServo)
            {
                // [2026-03-10] Servo 模式：正轉一格，讀當前角度 +step
                return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(M11 — Forward one pocket, SERVO mode — shortest path)
o<m11> sub

#<pockets> = {pockets}
o100 if [EXISTS[#<_ini[atc]pockets>]]
    #<pockets> = #<_ini[atc]pockets>
o100 endif

#<step> = [360.0 / #<pockets>]
#<current> = #<_hal[motion.analog-out-00]>
#<new_angle> = [#<current> + #<step>]
#3990 = [[#3990 MOD #<pockets>] + 1]

(PRINT, M11 SERVO FWD: pocket #3990 angle #<new_angle>)
M68 E0 Q[#<new_angle>]
G4 P0.5

o<m11> endsub [1]

M2
";
            }
            else
            {
                int doMotorFwd = config.Atc.DoMotorFwd;
                int diRotationIndex = config.Atc.DiRotationIndex;
                int sensorTimeout = config.Atc.SensorTimeout / 1000;
                return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(M11 — Forward one pocket, IO mode)
o<m11> sub

#<pockets> = {pockets}
o100 if [EXISTS[#<_ini[atc]pockets>]]
    #<pockets> = #<_ini[atc]pockets>
o100 endif

M64 P{doMotorFwd}
M66 P{diRotationIndex} L1 Q{sensorTimeout}
o110 if [#5399 EQ -1]
    M65 P{doMotorFwd}
    (abort, Failed to get rotation index - FWD timeout)
o110 endif
M65 P{doMotorFwd}

#3990 = [[#3990 MOD #<pockets>] + 1]

o<m11> endsub [1]

M2
";
            }
        }

        // [2026-03-09] --- m12.ngc Carousel 版（反轉一格）---
        private static string GenerateM12Carousel(MachineConfig config)
        {
            bool isServo = config.Atc.ControlMode == CarouselControlMode.Servo;
            int pockets = config.Atc.ToolCount;

            if (isServo)
            {
                // [2026-03-10] Servo 模式：反轉一格，讀當前角度 -step
                return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(M12 — Reverse one pocket, SERVO mode — shortest path)
o<m12> sub

#<pockets> = {pockets}
o100 if [EXISTS[#<_ini[atc]pockets>]]
    #<pockets> = #<_ini[atc]pockets>
o100 endif

#<step> = [360.0 / #<pockets>]
#<current> = #<_hal[motion.analog-out-00]>
#<new_angle> = [#<current> - #<step>]
#3990 = [[[#3990 - 2 + #<pockets>] MOD #<pockets>] + 1]

(PRINT, M12 SERVO REV: pocket #3990 angle #<new_angle>)
M68 E0 Q[#<new_angle>]
G4 P0.5

o<m12> endsub [1]

M2
";
            }
            else
            {
                int doMotorRev = config.Atc.DoMotorRev;
                int diRotationIndex = config.Atc.DiRotationIndex;
                int sensorTimeout = config.Atc.SensorTimeout / 1000;
                return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(M12 — Reverse one pocket, IO mode)
o<m12> sub

#<pockets> = {pockets}
o100 if [EXISTS[#<_ini[atc]pockets>]]
    #<pockets> = #<_ini[atc]pockets>
o100 endif

M64 P{doMotorRev}
M66 P{diRotationIndex} L1 Q{sensorTimeout}
o110 if [#5399 EQ -1]
    M65 P{doMotorRev}
    (abort, Failed to get rotation index - REV timeout)
o110 endif
M65 P{doMotorRev}

#3990 = [[[#3990 - 2 + #<pockets>] MOD #<pockets>] + 1]

o<m12> endsub [1]

M2
";
            }
        }

        // [2026-03-10] m24.ngc — 鬆刀（Drawbar Release）：氣壓 DO ON → 推開拉桿
        private static string GenerateM24Ngc(MachineConfig config)
        {
            int doDrawbar = config.Atc.DoDrawbar;
            double dwell = config.Atc.UnclampDwell / 1000.0;
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(M24 — Drawbar Release / Unclamp)
o<m24> sub
M64 P{doDrawbar}
G4 P{dwell:F1}
o<m24> endsub
M2
";
        }

        // [2026-03-10] m25.ngc — 夾刀（Drawbar Clamp）：氣壓 DO OFF → 彈簧夾緊
        private static string GenerateM25Ngc(MachineConfig config)
        {
            int doDrawbar = config.Atc.DoDrawbar;
            double dwell = config.Atc.ClampDwell / 1000.0;
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(M25 — Drawbar Clamp)
o<m25> sub
M65 P{doDrawbar}
G4 P{dwell:F1}
o<m25> endsub
M2
";
        }

        // [2026-03-10] --- extendatc.ngc（刀盤伸出）---
        private static string GenerateExtendAtcNgc(MachineConfig config)
        {
            int doCarouselOut = config.Atc.DoCarouselOut;
            int doCarouselHome = config.Atc.DoCarouselHome;
            int diCarouselOut = config.Atc.DiCarouselOut;
            int sensorTimeout = config.Atc.SensorTimeout / 1000;

            var sb = new StringBuilder();
            sb.AppendLine($"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})");
            sb.AppendLine("(extendatc — Extend carousel out)");
            sb.AppendLine("o<extendatc> sub");
            sb.AppendLine();
            sb.AppendLine($"M65 P{doCarouselHome}");
            sb.AppendLine($"M64 P{doCarouselOut}");

            if (!ConfigurationService.IsAtcSimulation)
            {
                sb.AppendLine($"M66 P{diCarouselOut} L3 Q{sensorTimeout}");
                sb.AppendLine("o100 if [#5399 EQ -1]");
                sb.AppendLine($"    M65 P{doCarouselOut}");
                sb.AppendLine("    (abort, Carousel extend timeout - sensor not triggered)");
                sb.AppendLine("o100 endif");
            }

            sb.AppendLine();
            sb.AppendLine("o<extendatc> endsub [1]");
            sb.AppendLine();
            sb.AppendLine("M2");
            return sb.ToString();
        }

        // [2026-03-10] --- retractatc.ngc（刀盤收回）---
        private static string GenerateRetractAtcNgc(MachineConfig config)
        {
            int doCarouselOut = config.Atc.DoCarouselOut;
            int doCarouselHome = config.Atc.DoCarouselHome;
            int diCarouselHome = config.Atc.DiCarouselHome;
            int sensorTimeout = config.Atc.SensorTimeout / 1000;

            var sb = new StringBuilder();
            sb.AppendLine($"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})");
            sb.AppendLine("(retractatc — Retract carousel in)");
            sb.AppendLine("o<retractatc> sub");
            sb.AppendLine();
            sb.AppendLine($"M65 P{doCarouselOut}");
            sb.AppendLine($"M64 P{doCarouselHome}");

            if (!ConfigurationService.IsAtcSimulation)
            {
                sb.AppendLine($"M66 P{diCarouselHome} L3 Q{sensorTimeout}");
                sb.AppendLine("o100 if [#5399 EQ -1]");
                sb.AppendLine($"    M65 P{doCarouselHome}");
                sb.AppendLine("    (abort, Carousel retract timeout - sensor not triggered)");
                sb.AppendLine("o100 endif");
            }

            sb.AppendLine();
            sb.AppendLine("o<retractatc> endsub [1]");
            sb.AppendLine();
            sb.AppendLine("M2");
            return sb.ToString();
        }

        // [2026-03-09] --- move_head_above_carousel.ngc ---
        private static string GenerateMoveHeadAboveCarouselNgc()
        {
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(move_head_above_carousel — Z to clearance height)
o<move_head_above_carousel> sub

#<z_clearance> = #3982
o100 if [EXISTS[#<_ini[atc]z_tool_clearance_height>]]
    #<z_clearance> = #<_ini[atc]z_tool_clearance_height>
o100 endif

G90
G0 G53 Z[#<z_clearance>]

o<move_head_above_carousel> endsub [1]

M2
";
        }

        // [2026-03-09] --- move_tool_to_carousel_height.ngc ---
        private static string GenerateMoveToolToCarouselHeightNgc()
        {
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(move_tool_to_carousel_height — Z to tool change height)
o<move_tool_to_carousel_height> sub

#<z_change> = #3981
o100 if [EXISTS[#<_ini[atc]z_tool_change_height>]]
    #<z_change> = #<_ini[atc]z_tool_change_height>
o100 endif

G90
G1 G53 F500 Z[#<z_change>]

o<move_tool_to_carousel_height> endsub [1]

M2
";
        }

        // [2026-03-09] --- program_coolant.ngc（換刀後恢復冷卻）---
        private static string GenerateProgramCoolantNgc()
        {
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
(program_coolant — restore coolant state after tool change)
o<program_coolant> sub
(placeholder — add coolant restore logic if needed)
o<program_coolant> endsub [1]

M2
";
        }
    }
}
