using System;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Collections.Generic;
using CncController.Models;

namespace CncController.Services
{
    public class ConfigurationService
    {
        public static ConfigurationService Instance { get; } = new ConfigurationService();

        private readonly HttpClient _http;
        private const string ConfigFileName = "MachineConfig.json";
        private readonly JsonSerializerOptions _jsonOptions;

        // [2026-03-05] 探針模擬開關：true=開發測試（HAL comp 模擬）, false=實機（硬體 probe-in）
        // 出廠前手動改為 false
        public const bool IsProbeSimulation = true;

        private ConfigurationService()
        {
            // [Item 11] 伺服器 URL 從 AppSettings 讀取，不再硬寫
            _http = new HttpClient { BaseAddress = new Uri(AppSettings.Instance.ServerUrl) };
            _jsonOptions = new JsonSerializerOptions { WriteIndented = true, PropertyNameCaseInsensitive = true };
        }

        public async Task<MachineConfig> LoadConfigAsync()
        {
            try
            {
                if (!File.Exists(ConfigFileName)) return new MachineConfig();
                string json = await File.ReadAllTextAsync(ConfigFileName);
                return JsonSerializer.Deserialize<MachineConfig>(json, _jsonOptions) ?? new MachineConfig();
            }
            catch (Exception ex)
            {
                AlarmService.Instance.AddLog("ERR", $"Config load failed: {ex.GetType().Name}: {ex.Message}");
                return new MachineConfig();
            }
        }

        public async Task SaveConfigAsync(MachineConfig config)
        {
            try
            {
                // 1. 儲存 JSON 設定檔
                string json = JsonSerializer.Serialize(config, _jsonOptions);
                await File.WriteAllTextAsync(ConfigFileName, json);

                // 2. 生成 LinuxCNC 所需檔案
                string iniContent = GenerateIni(config);
                string xmlContent = GenerateXml(config);
                string halContent = GenerateHal(config);
                string postGuiContent = GeneratePostGuiHal(config);
                // [2026-03-05] 探針模擬 HAL：僅模擬模式產出
                // [2026-03-05] 探針模擬 HAL：需要 config 判斷位置回饋訊號名稱
                string simProbeHalContent = IsProbeSimulation ? GenerateSimProbeHal(config) : null;

                var payload = new
                {
                    IniContent = iniContent,
                    HalContent = halContent,
                    XmlContent = xmlContent,
                    PostGuiContent = postGuiContent,
                    SimProbeHalContent = simProbeHalContent
                };

                // 3. 傳送至後端並重啟
                await _http.PostAsJsonAsync("/api/config/update", payload);
                await _http.PostAsync("/api/machine/restart", null);
            }
            catch (Exception ex)
            {
                // [安全] 改為寫入 AlarmService（跑馬燈可見），並重新拋出讓呼叫端知道部署失敗
                AlarmService.Instance.AddLog("ERR", $"SaveConfig failed: {ex.GetType().Name}: {ex.Message}");
                throw;
            }
        }

        // ========================================================================================
        // 1. 生成 INI
        // ========================================================================================
        private string GenerateIni(MachineConfig config)
        {
            var sb = new StringBuilder();
            int axesCount = config.Axes.Count;
            string coordinates = string.Join(" ", config.Axes.Select(a => a.AxisID));
            string geometry = string.Join("", config.Axes.Select(a => a.AxisID));

            // [2026-03-05] 生成時間戳記
            sb.AppendLine($"# Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("[EMC]");
            sb.AppendLine("VERSION = 1.1");
            sb.AppendLine("MACHINE = SGCAM_PB_ATC");
            sb.AppendLine("DEBUG = 0");
            sb.AppendLine();

            sb.AppendLine("[DISPLAY]");
            sb.AppendLine("DISPLAY = probe_basic");
            sb.AppendLine("OPEN_FILE = ~/linuxcnc/nc_files/probe_basic/examples/blank.ngc");
            sb.AppendLine("CONFIG_FILE = custom_config.yml");
            sb.AppendLine("CYCLE_TIME = 0.200");
            sb.AppendLine("POSITION_OFFSET = RELATIVE");
            sb.AppendLine("POSITION_FEEDBACK = ACTUAL");
            sb.AppendLine("MAX_FEED_OVERRIDE = 2.0");
            sb.AppendLine("MAX_SPINDLE_OVERRIDE = 2.0");
            sb.AppendLine("MIN_SPINDLE_OVERRIDE = 0.5");
            sb.AppendLine("DEFAULT_SPINDLE_SPEED = 300");
            sb.AppendLine("PROGRAM_PREFIX = ~/linuxcnc/nc_files");
            sb.AppendLine("INTRO_GRAPHIC = pbsplash.png");
            sb.AppendLine("INTRO_TIME = 3");
            sb.AppendLine("EDITOR = gedit");
            sb.AppendLine("INCREMENTS = JOG 0.1 0.01 0.001");
            sb.AppendLine($"GEOMETRY = {geometry}");
            sb.AppendLine($"DRO_DISPLAY = {geometry}");
            // [2026-03-03] 依啟用軸動態產生 OFFSET_COLUMNS，告訴 PB UI 表格顯示哪些軸
            sb.AppendLine($"OFFSET_COLUMNS = {coordinates}");
            sb.AppendLine("ATC_TAB_DISPLAY = 2");
            sb.AppendLine("USER_BUTTONS_PATH = user_buttons/");
            sb.AppendLine("USER_ATC_BUTTONS_PATH = user_atc_buttons/");
            sb.AppendLine("USER_DROS_PATH = user_dro_display/");
            sb.AppendLine();

            sb.AppendLine("[FILTER]");
            sb.AppendLine("PROGRAM_EXTENSION = .nc,.txt,.tap Other NC files");
            sb.AppendLine("png = image-to-gcode");
            sb.AppendLine();

            sb.AppendLine("[PYTHON]");
            sb.AppendLine("TOPLEVEL = ./python/toplevel.py");
            sb.AppendLine("PATH_APPEND = ./python/");
            sb.AppendLine();

            sb.AppendLine("[ATC]");
            sb.AppendLine("POCKETS = 12");
            sb.AppendLine();

            // [2026-03-05] 探針模擬設定（僅模擬模式產出）
            if (IsProbeSimulation)
            {
                sb.AppendLine("[PROBE]");
                sb.AppendLine("# Simulation mode — comp trigger positions managed by frontend");
                sb.AppendLine();
            }

            sb.AppendLine("[RS274NGC]");
            sb.AppendLine("RS274NGC_STARTUP_CODE = F10 S300 G21 G17 G40 G49 G54 G64 P0.001 G80 G90 G91.1 G92.1 G94 G97 G98");
            sb.AppendLine("PARAMETER_FILE = vmc_metric.var");
            sb.AppendLine("SUBROUTINE_PATH = macros_metric_sim");
            sb.AppendLine("REMAP=M6  modalgroup=6 prolog=change_prolog ngc=toolchange epilog=change_epilog");
            sb.AppendLine("REMAP=M10 modalgroup=6 argspec=P ngc=m10");
            sb.AppendLine("REMAP=M11 modalgroup=6 argspec=p ngc=m11");
            sb.AppendLine("REMAP=M12 modalgroup=6 argspec=p ngc=m12");
            sb.AppendLine("REMAP=M13 modalgroup=6 ngc=m13");
            sb.AppendLine("REMAP=M21 modalgroup=6 ngc=m21");
            sb.AppendLine("REMAP=M22 modalgroup=6 ngc=m22");
            sb.AppendLine("REMAP=M23 modalgroup=6 ngc=m23");
            sb.AppendLine("REMAP=M24 modalgroup=6 ngc=m24");
            sb.AppendLine("REMAP=M25 modalgroup=6 ngc=m25");
            sb.AppendLine("REMAP=M26 modalgroup=6 ngc=m26");
            sb.AppendLine();

            sb.AppendLine("[EMCMOT]");
            sb.AppendLine("EMCMOT = motmod");
            sb.AppendLine("COMM_TIMEOUT = 1.0");
            sb.AppendLine("BASE_PERIOD = 100000");
            sb.AppendLine("SERVO_PERIOD = 1000000");
            sb.AppendLine();

            sb.AppendLine("[TASK]");
            sb.AppendLine("TASK = milltask");
            sb.AppendLine("CYCLE_TIME = 0.010");
            sb.AppendLine();

            sb.AppendLine("[HAL]");
            sb.AppendLine("HALUI = halui");
            sb.AppendLine("HALFILE = 3axis.hal");
            // [2026-03-05] 探針模擬模式：載入 sim_probe.hal（3 軸 comp + or3 自動觸發）
            if (IsProbeSimulation)
            {
                sb.AppendLine("HALFILE = sim_probe.hal");
            }
            sb.AppendLine("POSTGUI_HALFILE = probe_basic_postgui.hal");
            sb.AppendLine();

            sb.AppendLine("[TRAJ]");
            sb.AppendLine($"AXES = {axesCount}");
            sb.AppendLine("SPINDLES = 1");
            sb.AppendLine($"COORDINATES = {coordinates}");
            sb.AppendLine("LINEAR_UNITS = mm");
            sb.AppendLine("ANGULAR_UNITS = degree");
            sb.AppendLine("DEFAULT_LINEAR_VELOCITY = 50");
            sb.AppendLine("MAX_LINEAR_VELOCITY = 125");
            sb.AppendLine();

            sb.AppendLine("[EMCIO]");
            sb.AppendLine("EMCIO = io");
            sb.AppendLine("CYCLE_TIME = 0.100");
            sb.AppendLine("TOOL_TABLE = tool_metric.tbl");
            sb.AppendLine("RANDOM_TOOLCHANGER = 0");
            sb.AppendLine();

            sb.AppendLine("[KINS]");
            sb.AppendLine($"JOINTS = {axesCount}");
            sb.AppendLine($"KINEMATICS = trivkins coordinates={geometry}");
            sb.AppendLine();

            sb.AppendLine("[SPINDLE]");
            sb.AppendLine("PGAIN_V = 0");
            sb.AppendLine("IGAIN_V = 0.01");
            sb.AppendLine("DGAIN_V = 0");
            sb.AppendLine("FF0_V = 1");
            sb.AppendLine("FF1_V = 0");
            sb.AppendLine("PGAIN_P = 100");
            sb.AppendLine("IGAIN_P = 1");
            sb.AppendLine("DGAIN_P = 0");
            sb.AppendLine("FF0_P = 0");
            sb.AppendLine("FF1_P = 1");
            sb.AppendLine();

            for (int i = 0; i < axesCount; i++)
            {
                var axis = config.Axes[i];
                string axisName = axis.AxisID.ToUpper();
                double pitch = axis.Pitch == 0 ? 5.0 : axis.Pitch;
                double scale = axis.PulsePerRev / pitch;

                sb.AppendLine($"# --- Axis {axisName} ---");
                sb.AppendLine($"[AXIS_{axisName}]");
                sb.AppendLine($"MIN_LIMIT = {axis.SoftLimitNeg}");
                sb.AppendLine($"MAX_LIMIT = {axis.SoftLimitPos}");
                sb.AppendLine($"MAX_VELOCITY = {axis.MaxVelocity}");
                sb.AppendLine($"MAX_ACCELERATION = {axis.MaxAcceleration}");
                sb.AppendLine();

                sb.AppendLine($"[JOINT_{i}]");
                sb.AppendLine("TYPE = LINEAR");
                sb.AppendLine("HOME = 0.0");
                sb.AppendLine($"MIN_LIMIT = {axis.SoftLimitNeg}");
                sb.AppendLine($"MAX_LIMIT = {axis.SoftLimitPos}");
                sb.AppendLine($"MAX_VELOCITY = {axis.MaxVelocity}");
                sb.AppendLine($"MAX_ACCELERATION = {axis.MaxAcceleration}");
                sb.AppendLine($"STEP_SCALE = {scale:0.0}");
                sb.AppendLine("FERROR = 50.0");
                sb.AppendLine("MIN_FERROR = 5.0");

                sb.AppendLine("P_GAIN = 1000");
                sb.AppendLine("I_GAIN = 0");
                sb.AppendLine("D_GAIN = 0");
                sb.AppendLine("FF0 = 0");
                sb.AppendLine("FF1 = 1.0");

                double searchVel = 0;
                double latchVel = 0;
                string useIndex = "NO";
                string ignoreLimits = "NO";

                switch (axis.HomingMode)
                {
                    case HomingMode.Immediate:
                        searchVel = 0; latchVel = 0; useIndex = "NO";
                        break;
                    case HomingMode.HomeSwitch:
                        searchVel = Math.Abs(axis.HomeSpeed) * axis.HomeDirection;
                        latchVel = Math.Abs(axis.HomeLatchSpeed) * axis.HomeDirection;
                        useIndex = axis.HomeUseIndex ? "YES" : "NO";
                        ignoreLimits = "YES";
                        break;
                    case HomingMode.LimitSwitch:
                        searchVel = Math.Abs(axis.HomeSpeed) * axis.HomeDirection;
                        latchVel = Math.Abs(axis.HomeLatchSpeed) * axis.HomeDirection;
                        useIndex = axis.HomeUseIndex ? "YES" : "NO";
                        ignoreLimits = "YES";
                        break;
                }

                sb.AppendLine($"HOME_OFFSET = {axis.HomeOffset}");
                sb.AppendLine($"HOME_SEARCH_VEL = {searchVel}");
                sb.AppendLine($"HOME_LATCH_VEL = {latchVel}");
                sb.AppendLine($"HOME_USE_INDEX = {useIndex}");
                sb.AppendLine($"HOME_IGNORE_LIMITS = {ignoreLimits}");
                sb.AppendLine($"HOME_SEQUENCE = {axis.HomeSequence}");
                sb.AppendLine();
            }
            return sb.ToString();
        }

        // ========================================================================================
        // 2. 生成 HAL (整合 IO Mappings 與標準訊號)
        // ========================================================================================
        private string GenerateHal(MachineConfig config)
        {
            var sb = new StringBuilder();
            int axesCount = config.Axes.Count;

            // [2026-03-05] 生成時間戳記
            sb.AppendLine($"# Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("loadrt [KINS]KINEMATICS");
            sb.AppendLine("loadrt [EMCMOT]EMCMOT servo_period_nsec=[EMCMOT]SERVO_PERIOD num_joints=[KINS]JOINTS");
            sb.AppendLine($"loadrt cia402 count={axesCount}");

            var sliceNames = string.Join(",", config.Axes.Select(a => $"slice_{a.AxisID}"));
            var personalities = string.Join(",", Enumerable.Repeat("32", axesCount));
            sb.AppendLine($"loadrt bitslice names={sliceNames} personality={personalities}");

            // 計算 NOT 元件總需求
            int axisNotCount = axesCount * 3;
            int ioInvertCount = config.Mappings
                .Where(m => m.Type == MapType.Input || m.Type == MapType.Output)
                .SelectMany(m => m.Pins)
                .Count(p => p.IsInverted);

            int totalNotCount = axisNotCount + ioInvertCount;

            if (totalNotCount > 0) sb.AppendLine($"loadrt not count={totalNotCount}");

            sb.AppendLine("loadusr -W lcec_conf ethercat-conf.xml");
            sb.AppendLine("loadrt lcec");
            sb.AppendLine();

            sb.AppendLine("addf lcec.read-all servo-thread");
            foreach (var axis in config.Axes) sb.AppendLine($"addf slice_{axis.AxisID} servo-thread");
            for (int i = 0; i < axesCount; i++) sb.AppendLine($"addf cia402.{i}.read-all servo-thread");

            if (totalNotCount > 0)
            {
                for (int k = 0; k < totalNotCount; k++) sb.AppendLine($"addf not.{k} servo-thread");
            }

            sb.AppendLine("addf motion-command-handler servo-thread");
            sb.AppendLine("addf motion-controller servo-thread");
            for (int i = 0; i < axesCount; i++) sb.AppendLine($"addf cia402.{i}.write-all servo-thread");
            sb.AppendLine("addf lcec.write-all servo-thread");
            sb.AppendLine();

            int currentNotIndex = 0;

            // =========================================================
            // A. 軸與馬達邏輯 (AXIS MAPPING)
            // =========================================================
            for (int i = 0; i < axesCount; i++)
            {
                var axis = config.Axes[i];
                string axisHalName = $"joint.{i}";

                // [2026-02-24] 修正：從 Mappings 動態取得 EtherCAT Slave Index，不再寫死 X→0, Y→2, Z→3
                // [2026-03-05] 修正：LogicalName 格式為 "X Axis"，需用 StartsWith 匹配 AxisID "X"
                string axName = axis.AxisID.ToUpper();
                var axisMapping = config.Mappings.FirstOrDefault(m =>
                    m.Type == MapType.Axis && m.LogicalName.StartsWith(axis.AxisID, StringComparison.OrdinalIgnoreCase));
                int sIdx;
                if (axisMapping != null)
                {
                    sIdx = axisMapping.PhysicalIndex;
                }
                else
                {
                    // 無映射時回退為 Joint Index（向後相容）
                    sIdx = axis.Index;
                    AlarmService.Instance.AddLog("WARN", $"No axis mapping found for {axis.AxisID}, fallback to slave index {sIdx}");
                }

                string sliceName = $"slice_{axis.AxisID}";

                // [2026-03-05] 重構：使用 ClassifyDevice() 統一設備類型判斷
                var map = config.Mappings.FirstOrDefault(m => m.PhysicalIndex == sIdx && m.Type == MapType.Axis)
                       ?? config.Mappings.FirstOrDefault(m => m.PhysicalIndex == sIdx);
                var deviceType = SlaveDeviceType.Unknown;
                // [2026-03-05] 傳入 DeviceCategory 優先用掃描結果判斷
                if (map != null) deviceType = ClassifyDevice(map.ExpectedVendorId, map.ExpectedProductCode, map.DeviceCategory);
                bool isServo = deviceType == SlaveDeviceType.Servo || deviceType == SlaveDeviceType.PulseGenerator;
                bool isPulseGen = deviceType == SlaveDeviceType.PulseGenerator;

                sb.AppendLine($"# --- Axis {axis.AxisID} (Slave {sIdx}) [Type: {(isServo ? "Servo" : "Stepper/OpenLoop")}] ---");

                sb.AppendLine($"net {axis.AxisID}-enable  {axisHalName}.amp-enable-out => cia402.{i}.enable");
                sb.AppendLine($"net {axis.AxisID}-control cia402.{i}.controlword => lcec.0.{sIdx}.control_word_J{sIdx}");
                sb.AppendLine($"net {axis.AxisID}-status  lcec.0.{sIdx}.status_word_J{sIdx} => cia402.{i}.statusword");

                sb.AppendLine($"setp cia402.{i}.csp-mode 1");

                // ★★★ [修正] 只有「不是」5621 才設定 Operation Mode ★★★
                if (isServo && !isPulseGen)
                {
                    sb.AppendLine($"setp lcec.0.{sIdx}.modes_of_operation_J{sIdx} 8");
                }

                sb.AppendLine($"setp cia402.{i}.pos-scale [JOINT_{i}]STEP_SCALE");

                sb.AppendLine($"net {axis.AxisID}-pos-cmd {axisHalName}.motor-pos-cmd => cia402.{i}.pos-cmd");
                sb.AppendLine($"net {axis.AxisID}-drv-target cia402.{i}.drv-target-position => lcec.0.{sIdx}.target_position_J{sIdx}");

                sb.AppendLine($"net {axis.AxisID}-pos-fb lcec.0.{sIdx}.position_actual_value_J{sIdx} => cia402.{i}.drv-actual-position");

                if (isServo && !isPulseGen)
                {
                    sb.AppendLine("# [Feedback] Real Encoder Feedback (Closed Loop)");
                    sb.AppendLine($"net {axis.AxisID}-pos-fb-final cia402.{i}.pos-fb => {axisHalName}.motor-pos-fb");
                }
                else
                {
                    sb.AppendLine("# [Feedback] Fake Feedback (Open Loop)");
                    sb.AppendLine($"net {axis.AxisID}-pos-cmd => {axisHalName}.motor-pos-fb");
                }

                sb.AppendLine($"net {axis.AxisID}-di-raw lcec.0.{sIdx}.digital_inputs_J{sIdx} => {sliceName}.in");

                // --- Homing & Limits Logic ---
                if (axis.HomingMode == HomingMode.Immediate)
                {
                    sb.AppendLine("# Homing: Immediate");
                }
                else if (axis.HomingMode == HomingMode.HomeSwitch)
                {
                    if (axis.HomeSwitchLogic != LimitLogic.NotUsed)
                    {
                        string rawHomeSig = $"{sliceName}.out-{axis.HomeDiIndex:00}";
                        if (axis.HomeSwitchLogic == LimitLogic.NC)
                        {
                            sb.AppendLine($"net {axis.AxisID}-home-raw {rawHomeSig} => not.{currentNotIndex}.in");
                            sb.AppendLine($"net {axis.AxisID}-home {axisHalName}.home-sw-in <= not.{currentNotIndex}.out");
                            currentNotIndex++;
                        }
                        else
                        {
                            sb.AppendLine($"net {axis.AxisID}-home {axisHalName}.home-sw-in <= {rawHomeSig}");
                        }
                    }
                }
                else if (axis.HomingMode == HomingMode.LimitSwitch)
                {
                    int targetDiIndex = (axis.HomeDirection > 0) ? axis.PosLimitDiIndex : axis.NegLimitDiIndex;
                    if (axis.LimitSwitchLogic != LimitLogic.NotUsed)
                    {
                        string rawSharedSig = $"{sliceName}.out-{targetDiIndex:00}";
                        if (axis.LimitSwitchLogic == LimitLogic.NC)
                        {
                            sb.AppendLine($"net {axis.AxisID}-home-shared-raw {rawSharedSig} => not.{currentNotIndex}.in");
                            sb.AppendLine($"net {axis.AxisID}-home {axisHalName}.home-sw-in <= not.{currentNotIndex}.out");
                            currentNotIndex++;
                        }
                        else
                        {
                            sb.AppendLine($"net {axis.AxisID}-home {axisHalName}.home-sw-in <= {rawSharedSig}");
                        }
                    }
                }

                if (axis.LimitSwitchLogic != LimitLogic.NotUsed)
                {
                    string rawNeg = $"{sliceName}.out-{axis.NegLimitDiIndex:00}";
                    if (axis.LimitSwitchLogic == LimitLogic.NC)
                    {
                        sb.AppendLine($"net {axis.AxisID}-neg-raw {rawNeg} => not.{currentNotIndex}.in");
                        sb.AppendLine($"net {axis.AxisID}-neg-lim {axisHalName}.neg-lim-sw-in <= not.{currentNotIndex}.out");
                        currentNotIndex++;
                    }
                    else
                    {
                        sb.AppendLine($"net {axis.AxisID}-neg-lim {axisHalName}.neg-lim-sw-in <= {rawNeg}");
                    }

                    string rawPos = $"{sliceName}.out-{axis.PosLimitDiIndex:00}";
                    if (axis.LimitSwitchLogic == LimitLogic.NC)
                    {
                        sb.AppendLine($"net {axis.AxisID}-pos-raw {rawPos} => not.{currentNotIndex}.in");
                        sb.AppendLine($"net {axis.AxisID}-pos-lim {axisHalName}.pos-lim-sw-in <= not.{currentNotIndex}.out");
                        currentNotIndex++;
                    }
                    else
                    {
                        sb.AppendLine($"net {axis.AxisID}-pos-lim {axisHalName}.pos-lim-sw-in <= {rawPos}");
                    }
                }
                sb.AppendLine();
            }

            // =========================================================
            // ★★★ B. 標準系統訊號來源 (Standard Signals) ★★★
            // =========================================================
            sb.AppendLine("# === STANDARD SIGNALS (Source) ===");
            sb.AppendLine("net coolant-flood iocontrol.0.coolant-flood");
            sb.AppendLine("net coolant-mist  iocontrol.0.coolant-mist");
            sb.AppendLine("net spindle-on    spindle.0.on");
            sb.AppendLine("net spindle-cw    spindle.0.forward");
            sb.AppendLine("net spindle-ccw   spindle.0.reverse");
            sb.AppendLine("net spindle-brake spindle.0.brake");
            sb.AppendLine();

            // =========================================================
            // C. 通用 IO 邏輯 (IN/OUT MAPPINGS)
            // =========================================================
            sb.AppendLine("# === GENERAL IO MAPPINGS ===");

            // 處理 INPUT
            foreach (var map in config.Mappings.Where(m => m.Type == MapType.Input))
            {
                string devicePrefix = $"lcec.0.{map.PhysicalIndex}";
                sb.AppendLine($"# Input Group {map.ChannelIndex} (Slave {map.PhysicalIndex})");

                foreach (var pin in map.Pins)
                {
                    string hwPin = $"{devicePrefix}.din-{pin.Index:00}";
                    string signalName = string.IsNullOrWhiteSpace(pin.Function)
                        ? $"input-G{map.ChannelIndex}-{pin.Index:00}"
                        : CleanSignalName(pin.Function);

                    // [2026-03-05] 模擬模式：跳過 probe-in 整條接線（由 sim_probe.hal 建立）
                    if (signalName == "probe-in" && IsProbeSimulation)
                    {
                        sb.AppendLine($"# [SIM] skipped: net {signalName} {hwPin} (handled by sim_probe.hal)");
                        continue;
                    }

                    if (pin.IsInverted)
                    {
                        sb.AppendLine($"net raw-{signalName} {hwPin} => not.{currentNotIndex}.in");
                        sb.AppendLine($"net {signalName} not.{currentNotIndex}.out");
                        currentNotIndex++;
                    }
                    else
                    {
                        sb.AppendLine($"net {signalName} {hwPin}");
                    }

                    // [2026-03-05] 實機模式：probe-in → motion.probe-input
                    if (signalName == "probe-in")
                    {
                        sb.AppendLine($"net {signalName} => motion.probe-input");
                    }
                }
                sb.AppendLine();
            }

            // 處理 OUTPUT
            foreach (var map in config.Mappings.Where(m => m.Type == MapType.Output))
            {
                string devicePrefix = $"lcec.0.{map.PhysicalIndex}";
                sb.AppendLine($"# Output Group {map.ChannelIndex} (Slave {map.PhysicalIndex})");

                foreach (var pin in map.Pins)
                {
                    string hwPin = $"{devicePrefix}.dout-{pin.Index:00}";
                    string signalName = string.IsNullOrWhiteSpace(pin.Function)
                        ? $"output-G{map.ChannelIndex}-{pin.Index:00}"
                        : CleanSignalName(pin.Function);

                    if (pin.IsInverted)
                    {
                        sb.AppendLine($"net {signalName} => not.{currentNotIndex}.in");
                        sb.AppendLine($"net inv-{signalName} not.{currentNotIndex}.out => {hwPin}");
                        currentNotIndex++;
                    }
                    else
                    {
                        sb.AppendLine($"net {signalName} => {hwPin}");
                    }
                }
                sb.AppendLine();
            }

            sb.AppendLine();
            sb.AppendLine("# --- SAFETY BYPASS (FORCE CONNECTION) ---");
            sb.AppendLine("unlinkp iocontrol.0.emc-enable-in");
            sb.AppendLine("net logic-enable iocontrol.0.user-enable-out => iocontrol.0.emc-enable-in");

            return sb.ToString();
        }

        // ========================================================================================
        // 3. 生成 XML (EtherCAT Topology - 修正混合模組與脈波模組)
        // ========================================================================================
        private string GenerateXml(MachineConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            // [2026-03-05] 生成時間戳記
            sb.AppendLine($"<!-- Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss} -->");
            sb.AppendLine("<masters>");
            sb.AppendLine($"  <master idx=\"0\" appTimePeriod=\"1000000\" refClockSyncCycles=\"1000\">");

            int maxSlaveIndex = 0;
            if (config.Mappings.Any())
                maxSlaveIndex = config.Mappings.Max(m => m.PhysicalIndex);
            if (maxSlaveIndex < 1) maxSlaveIndex = 1;

            for (int i = 0; i <= maxSlaveIndex; i++)
            {
                // 1. 找出這個 Slave Index 所有相關的設定 (可能同時有 IN 和 OUT)
                var slaveMappings = config.Mappings.Where(m => m.PhysicalIndex == i).ToList();

                // [2026-03-05] 修正：優先取 Axis mapping，確保 isServo 判斷正確（避免取到 IO mapping）
                var mainMap = slaveMappings.FirstOrDefault(m => m.Type == MapType.Axis)
                           ?? slaveMappings.FirstOrDefault();

                if (mainMap != null)
                {
                    // [2026-03-05] 重構：使用 ClassifyDevice() 統一設備類型判斷（傳入 DeviceCategory 優先）
                    var deviceType = ClassifyDevice(mainMap.ExpectedVendorId, mainMap.ExpectedProductCode, mainMap.DeviceCategory);

                    // [2026-03-05] 擴充：依設備類型 switch 生成對應 XML
                    switch (deviceType)
                    {
                        case SlaveDeviceType.Coupler:
                            // Coupler：不配置 PDO
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"false\"/>");
                            break;

                        case SlaveDeviceType.Servo:
                        case SlaveDeviceType.PulseGenerator:
                        {
                            bool isPulseGen = deviceType == SlaveDeviceType.PulseGenerator;
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x300\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");

                            // CiA 402 Output PDOs
                            sb.AppendLine("      <syncManager idx=\"2\" dir=\"out\">");
                            sb.AppendLine("        <pdo idx=\"1600\">");
                            sb.AppendLine($"          <pdoEntry idx=\"6040\" subIdx=\"00\" bitLen=\"16\" halPin=\"control_word_J{i}\" halType=\"u32\"/>");
                            sb.AppendLine($"          <pdoEntry idx=\"607a\" subIdx=\"00\" bitLen=\"32\" halPin=\"target_position_J{i}\" halType=\"s32\"/>");
                            if (!isPulseGen)
                                sb.AppendLine($"          <pdoEntry idx=\"6060\" subIdx=\"00\" bitLen=\"8\" halPin=\"modes_of_operation_J{i}\" halType=\"s32\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");

                            // CiA 402 Input PDOs
                            sb.AppendLine("      <syncManager idx=\"3\" dir=\"in\">");
                            sb.AppendLine("        <pdo idx=\"1a00\">");
                            sb.AppendLine($"          <pdoEntry idx=\"6041\" subIdx=\"00\" bitLen=\"16\" halPin=\"status_word_J{i}\" halType=\"u32\"/>");
                            sb.AppendLine($"          <pdoEntry idx=\"6064\" subIdx=\"00\" bitLen=\"32\" halPin=\"position_actual_value_J{i}\" halType=\"s32\"/>");
                            if (!isPulseGen)
                                sb.AppendLine($"          <pdoEntry idx=\"6061\" subIdx=\"00\" bitLen=\"8\" halPin=\"modes_of_operation_display_J{i}\" halType=\"s32\"/>");
                            sb.AppendLine($"          <pdoEntry idx=\"60fd\" subIdx=\"00\" bitLen=\"32\" halPin=\"digital_inputs_J{i}\" halType=\"u32\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        case SlaveDeviceType.IoModule:
                        {
                            // DI+DO 混合 IO（台達 R2-EC0902）— Free Run + 32x din + 32x dout
                            bool hasInput = slaveMappings.Any(m => m.Type == MapType.Input);
                            bool hasOutput = slaveMappings.Any(m => m.Type == MapType.Output);
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x0\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");

                            // Output 32 bits
                            if (hasOutput || true) // IoModule 永遠生成 IO
                            {
                                sb.AppendLine("      <syncManager idx=\"2\" dir=\"out\">");
                                sb.AppendLine("        <pdo idx=\"1600\">");
                                for (int k = 0; k < 32; k++)
                                    sb.AppendLine($"          <pdoEntry idx=\"0x7000\" subIdx=\"0x{k + 1:X2}\" bitLen=\"1\" halPin=\"dout-{k:00}\" halType=\"bit\"/>");
                                sb.AppendLine("        </pdo>");
                                sb.AppendLine("      </syncManager>");
                            }

                            // Input 32 bits
                            if (hasInput || true) // IoModule 永遠生成 IO
                            {
                                sb.AppendLine("      <syncManager idx=\"3\" dir=\"in\">");
                                sb.AppendLine("        <pdo idx=\"1a00\">");
                                for (int k = 0; k < 32; k++)
                                    sb.AppendLine($"          <pdoEntry idx=\"0x6000\" subIdx=\"0x{k + 1:X2}\" bitLen=\"1\" halPin=\"din-{k:00}\" halType=\"bit\"/>");
                                sb.AppendLine("        </pdo>");
                                sb.AppendLine("      </syncManager>");
                            }
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        case SlaveDeviceType.DigitalInput:
                        {
                            // DI-only — Free Run + 32x din
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x0\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");
                            sb.AppendLine("      <syncManager idx=\"3\" dir=\"in\">");
                            sb.AppendLine("        <pdo idx=\"1a00\">");
                            for (int k = 0; k < 32; k++)
                                sb.AppendLine($"          <pdoEntry idx=\"0x6000\" subIdx=\"0x{k + 1:X2}\" bitLen=\"1\" halPin=\"din-{k:00}\" halType=\"bit\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        case SlaveDeviceType.DigitalOutput:
                        {
                            // DO-only — Free Run + 32x dout
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x0\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");
                            sb.AppendLine("      <syncManager idx=\"2\" dir=\"out\">");
                            sb.AppendLine("        <pdo idx=\"1600\">");
                            for (int k = 0; k < 32; k++)
                                sb.AppendLine($"          <pdoEntry idx=\"0x7000\" subIdx=\"0x{k + 1:X2}\" bitLen=\"1\" halPin=\"dout-{k:00}\" halType=\"bit\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        case SlaveDeviceType.Mpg:
                        {
                            // MPG 手輪 — Free Run + mpg-buttons (6000:01) + mpg-counts (6064:00)
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x0\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");
                            sb.AppendLine("      <syncManager idx=\"3\" dir=\"in\">");
                            sb.AppendLine("        <pdo idx=\"1a00\">");
                            sb.AppendLine("          <pdoEntry idx=\"6000\" subIdx=\"01\" bitLen=\"16\" halPin=\"mpg-buttons\" halType=\"u32\"/>");
                            sb.AppendLine("          <pdoEntry idx=\"6064\" subIdx=\"00\" bitLen=\"32\" halPin=\"mpg-counts\" halType=\"s32\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        default: // Unknown
                        {
                            // 安全預設：DC Sync 0x300，無 PDO
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x300\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");
                            sb.AppendLine("    </slave>");
                            break;
                        }
                    }
                }
                else
                {
                    // Empty Slave
                    sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"000001dd\" pid=\"00005500\" configPdos=\"false\"/>");
                }
            }

            sb.AppendLine("  </master>");
            sb.AppendLine("</masters>");
            return sb.ToString();
        }

        private string GeneratePostGuiHal(MachineConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Generated by CncController - PostGUI");
            sb.AppendLine("# 這裡只負責將 HAL 訊號連接到 Probe Basic 介面");
            sb.AppendLine("# ★★★ 絕對不要在這裡 loadrt not/bitslice，因為主 HAL 已經載入了 ★★★");
            sb.AppendLine();
            return sb.ToString();
        }

        // [2026-03-05] 重構：ClassifyDevice() 取代 IsServoDrive()，統一設備類型判斷邏輯
        // [2026-03-05] 新增 deviceCategory 參數：優先用後端掃描結果，fallback VID/PID 比對
        private static SlaveDeviceType ClassifyDevice(string vidStr, string pidStr, string deviceCategory = "")
        {
            // 優先用後端掃描結果的 Category（新設定檔已儲存）
            if (!string.IsNullOrEmpty(deviceCategory))
            {
                return deviceCategory switch
                {
                    Models.DeviceCategory.Servo    => SlaveDeviceType.Servo,
                    Models.DeviceCategory.PulseGen => SlaveDeviceType.PulseGenerator,
                    Models.DeviceCategory.DiDo     => SlaveDeviceType.IoModule,
                    Models.DeviceCategory.DigIn    => SlaveDeviceType.DigitalInput,
                    Models.DeviceCategory.DigOut   => SlaveDeviceType.DigitalOutput,
                    Models.DeviceCategory.Mpg      => SlaveDeviceType.Mpg,
                    Models.DeviceCategory.Coupler  => SlaveDeviceType.Coupler,
                    _                              => SlaveDeviceType.Unknown,
                };
            }

            // Fallback：用 VID/PID 字串比對（手動建立映射或舊設定檔相容）
            if (string.IsNullOrEmpty(pidStr)) return SlaveDeviceType.Unknown;
            string p = pidStr.ToLower().Trim().Replace("0x", "");
            string v = vidStr?.ToLower().Trim().Replace("0x", "") ?? "";

            // 匯川伺服
            if (p.Contains("c010d") || p.Contains("916")) return SlaveDeviceType.Servo;

            // 台達系列
            if (v.Contains("1dd"))
            {
                if (p.Contains("902"))  return SlaveDeviceType.IoModule;       // R2-EC0902
                if (p.Contains("5621")) return SlaveDeviceType.PulseGenerator; // 5621
                return SlaveDeviceType.Servo;                                   // 6080 等
            }

            return SlaveDeviceType.Unknown;
        }

        private string CleanSignalName(string name)
        {
            if (string.IsNullOrEmpty(name)) return "unknown";
            char[] arr = name.ToCharArray();
            arr = Array.FindAll(arr, (c => (char.IsLetterOrDigit(c) || c == '_' || c == '-')));
            return new string(arr).Trim().Replace(" ", "-");
        }

        // ========================================================================================
        // [2026-03-05] 生成 sim_probe.hal — 探針模擬接線（3 軸 comp + or2 串聯）
        // RT 模組（comp/or2）由 simulated_home_probe_basic.hal 集中載入
        // ========================================================================================
        // [2026-03-05] 生成自包含的 sim_probe.hal（loadrt + addf + 接線全部在此）
        // 需要 config 判斷位置回饋訊號名稱（servo → {AxisID}-pos-fb-final, pulseGen → {AxisID}-pos-cmd）
        // [2026-03-06] 簡化探針模擬 HAL：移除 near/or2 自動觸發架構，改用手動 signal
        //              前端按鈕透過 /v2/hal/setp 設定 probe-in = 1/0，使用者自行控制觸發時機
        private string GenerateSimProbeHal(MachineConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("# Probe Simulation HAL (manual trigger mode)");
            sb.AppendLine("# User toggles probe-in signal via frontend button");
            sb.AppendLine();
            sb.AppendLine("# 建立 probe-in signal 並連接 motion.probe-input（預設 0 = 未觸發）");
            sb.AppendLine("net probe-in motion.probe-input");
            sb.AppendLine("sets probe-in 0");
            return sb.ToString();
        }
    }
}