using System;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Collections.Generic;
using CncController.Models;

namespace CncController.Services
{
    public class ConfigurationService
    {
        public static ConfigurationService Instance { get; } = new ConfigurationService();

        private readonly HttpClient _http;
        private const string ConfigFileName = "MachineConfig.json";
        private readonly JsonSerializerOptions _jsonOptions;

        // [2026-03-05] 探針模擬開關：true=開發測試（HAL comp 模擬）, false=實機（硬體 probe-in）
        // 出廠前手動改為 false
        public const bool IsProbeSimulation = true;

        private ConfigurationService()
        {
            // [Item 11] 伺服器 URL 從 AppSettings 讀取，不再硬寫
            _http = new HttpClient { BaseAddress = new Uri(AppSettings.Instance.ServerUrl) };
            _jsonOptions = new JsonSerializerOptions { WriteIndented = true, PropertyNameCaseInsensitive = true };
        }

        public async Task<MachineConfig> LoadConfigAsync()
        {
            try
            {
                if (!File.Exists(ConfigFileName)) return new MachineConfig();
                string json = await File.ReadAllTextAsync(ConfigFileName);
                return JsonSerializer.Deserialize<MachineConfig>(json, _jsonOptions) ?? new MachineConfig();
            }
            catch (Exception ex)
            {
                AlarmService.Instance.AddLog("ERR", $"Config load failed: {ex.GetType().Name}: {ex.Message}");
                return new MachineConfig();
            }
        }

        public async Task SaveConfigAsync(MachineConfig config)
        {
            try
            {
                // 1. 儲存 JSON 設定檔
                string json = JsonSerializer.Serialize(config, _jsonOptions);
                await File.WriteAllTextAsync(ConfigFileName, json);

                // 2. 生成 LinuxCNC 所需檔案
                string iniContent = GenerateIni(config);
                string xmlContent = GenerateXml(config);
                string halContent = GenerateHal(config);
                string postGuiContent = GeneratePostGuiHal(config);
                // [2026-03-05] 探針模擬 HAL：僅模擬模式產出
                // [2026-03-05] 探針模擬 HAL：需要 config 判斷位置回饋訊號名稱
                string simProbeHalContent = IsProbeSimulation ? GenerateSimProbeHal(config) : null;

                // [2026-03-09] ATC NGC 巨集：依 AtcType 動態生成 4 個類型相關檔案
                var atcNgcFiles = GenerateAtcNgc(config);

                var payload = new
                {
                    IniContent = iniContent,
                    HalContent = halContent,
                    XmlContent = xmlContent,
                    PostGuiContent = postGuiContent,
                    SimProbeHalContent = simProbeHalContent,
                    // [2026-03-09] NGC 巨集內容（Dictionary<檔名, 內容>）
                    NgcFiles = atcNgcFiles
                };

                // 3. 傳送至後端並重啟
                await _http.PostAsJsonAsync("/api/config/update", payload);
                await _http.PostAsync("/api/machine/restart", null);
            }
            catch (Exception ex)
            {
                // [安全] 改為寫入 AlarmService（跑馬燈可見），並重新拋出讓呼叫端知道部署失敗
                AlarmService.Instance.AddLog("ERR", $"SaveConfig failed: {ex.GetType().Name}: {ex.Message}");
                throw;
            }
        }

        // ========================================================================================
        // 1. 生成 INI
        // ========================================================================================
        private string GenerateIni(MachineConfig config)
        {
            var sb = new StringBuilder();
            int axesCount = config.Axes.Count;
            string coordinates = string.Join(" ", config.Axes.Select(a => a.AxisID));
            string geometry = string.Join("", config.Axes.Select(a => a.AxisID));

            // [2026-03-05] 生成時間戳記
            sb.AppendLine($"# Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("[EMC]");
            sb.AppendLine("VERSION = 1.1");
            sb.AppendLine("MACHINE = SGCAM_PB_ATC");
            sb.AppendLine("DEBUG = 0");
            sb.AppendLine();

            sb.AppendLine("[DISPLAY]");
            sb.AppendLine("DISPLAY = probe_basic");
            sb.AppendLine("OPEN_FILE = ~/linuxcnc/nc_files/probe_basic/examples/blank.ngc");
            sb.AppendLine("CONFIG_FILE = custom_config.yml");
            sb.AppendLine("CYCLE_TIME = 0.200");
            sb.AppendLine("POSITION_OFFSET = RELATIVE");
            sb.AppendLine("POSITION_FEEDBACK = ACTUAL");
            sb.AppendLine("MAX_FEED_OVERRIDE = 2.0");
            sb.AppendLine("MAX_SPINDLE_OVERRIDE = 2.0");
            sb.AppendLine("MIN_SPINDLE_OVERRIDE = 0.5");
            sb.AppendLine("DEFAULT_SPINDLE_SPEED = 300");
            sb.AppendLine("PROGRAM_PREFIX = ~/linuxcnc/nc_files");
            sb.AppendLine("INTRO_GRAPHIC = pbsplash.png");
            sb.AppendLine("INTRO_TIME = 3");
            sb.AppendLine("EDITOR = gedit");
            sb.AppendLine("INCREMENTS = JOG 0.1 0.01 0.001");
            sb.AppendLine($"GEOMETRY = {geometry}");
            sb.AppendLine($"DRO_DISPLAY = {geometry}");
            // [2026-03-03] 依啟用軸動態產生 OFFSET_COLUMNS，告訴 PB UI 表格顯示哪些軸
            sb.AppendLine($"OFFSET_COLUMNS = {coordinates}");
            // [2026-03-09] ATC_TAB_DISPLAY 依刀庫類型動態切換：None→0, Umbrella→1, Turret→2
            int atcTabDisplay = config.Atc.Type switch
            {
                AtcType.Umbrella => 1,
                AtcType.Turret => 2,
                _ => 0
            };
            sb.AppendLine($"ATC_TAB_DISPLAY = {atcTabDisplay}");
            sb.AppendLine("USER_BUTTONS_PATH = user_buttons/");
            sb.AppendLine("USER_ATC_BUTTONS_PATH = user_atc_buttons/");
            sb.AppendLine("USER_DROS_PATH = user_dro_display/");
            sb.AppendLine();

            sb.AppendLine("[FILTER]");
            sb.AppendLine("PROGRAM_EXTENSION = .nc,.txt,.tap Other NC files");
            sb.AppendLine("png = image-to-gcode");
            sb.AppendLine();

            sb.AppendLine("[PYTHON]");
            sb.AppendLine("TOPLEVEL = ./python/toplevel.py");
            sb.AppendLine("PATH_APPEND = ./python/");
            sb.AppendLine();

            // [2026-03-09] [ATC] 參數化：依 AtcConfig 動態生成
            sb.AppendLine("[ATC]");
            sb.AppendLine($"POCKETS = {config.Atc.ToolCount}");
            sb.AppendLine($"Z_TOOL_CHANGE_HEIGHT = {config.Atc.ZToolChangeHeight}");
            sb.AppendLine($"Z_TOOL_CLEARANCE_HEIGHT = {config.Atc.ZClearanceHeight}");
            if (config.Atc.Type == AtcType.Turret)
            {
                // Rack 專用參數（寫入 INI 供 NGC 讀取）
                sb.AppendLine($"RACK_TRAVERSE_SPEED = {config.Atc.RackTraverseSpeed}");
                sb.AppendLine($"RACK_POCKET_1_X = {config.Atc.RackPocket1X}");
                sb.AppendLine($"RACK_POCKET_1_Y = {config.Atc.RackPocket1Y}");
                sb.AppendLine($"RACK_POCKET_2_X = {config.Atc.RackPocket2X}");
                sb.AppendLine($"RACK_POCKET_2_Y = {config.Atc.RackPocket2Y}");
                sb.AppendLine($"RACK_CLEARANCE_X = {config.Atc.RackClearanceX}");
                sb.AppendLine($"RACK_CLEARANCE_Y = {config.Atc.RackClearanceY}");
            }
            sb.AppendLine();

            // [2026-03-05] 探針模擬設定（僅模擬模式產出）
            if (IsProbeSimulation)
            {
                sb.AppendLine("[PROBE]");
                sb.AppendLine("# Simulation mode — comp trigger positions managed by frontend");
                sb.AppendLine();
            }

            sb.AppendLine("[RS274NGC]");
            sb.AppendLine("RS274NGC_STARTUP_CODE = F10 S300 G21 G17 G40 G49 G54 G64 P0.001 G80 G90 G91.1 G92.1 G94 G97 G98");
            sb.AppendLine("PARAMETER_FILE = vmc_metric.var");
            sb.AppendLine("SUBROUTINE_PATH = macros_metric_sim");
            // [2026-03-09] REMAP：有刀庫時才啟用 M6/M10~M26 重映射
            if (config.Atc.Type != AtcType.None)
            {
                sb.AppendLine("REMAP=M6  modalgroup=6 prolog=change_prolog ngc=toolchange epilog=change_epilog");
                sb.AppendLine("REMAP=M10 modalgroup=6 argspec=P ngc=m10");
                sb.AppendLine("REMAP=M11 modalgroup=6 argspec=p ngc=m11");
                sb.AppendLine("REMAP=M12 modalgroup=6 argspec=p ngc=m12");
                sb.AppendLine("REMAP=M13 modalgroup=6 ngc=m13");
                sb.AppendLine("REMAP=M21 modalgroup=6 ngc=m21");
                sb.AppendLine("REMAP=M22 modalgroup=6 ngc=m22");
                sb.AppendLine("REMAP=M23 modalgroup=6 ngc=m23");
                sb.AppendLine("REMAP=M24 modalgroup=6 ngc=m24");
                sb.AppendLine("REMAP=M25 modalgroup=6 ngc=m25");
                sb.AppendLine("REMAP=M26 modalgroup=6 ngc=m26");
            }
            sb.AppendLine();

            sb.AppendLine("[EMCMOT]");
            sb.AppendLine("EMCMOT = motmod");
            sb.AppendLine("COMM_TIMEOUT = 1.0");
            sb.AppendLine("BASE_PERIOD = 100000");
            sb.AppendLine("SERVO_PERIOD = 1000000");
            // [2026-03-09] NUM_DIO：ATC 用 M64/M65/M66 需要足夠的 digital IO pin（預設僅 4 個）
            sb.AppendLine("NUM_DIO = 32");
            sb.AppendLine();

            sb.AppendLine("[TASK]");
            sb.AppendLine("TASK = milltask");
            sb.AppendLine("CYCLE_TIME = 0.010");
            sb.AppendLine();

            sb.AppendLine("[HAL]");
            sb.AppendLine("HALUI = halui");
            sb.AppendLine("HALFILE = 3axis.hal");
            // [2026-03-05] 探針模擬模式：載入 sim_probe.hal（3 軸 comp + or3 自動觸發）
            if (IsProbeSimulation)
            {
                sb.AppendLine("HALFILE = sim_probe.hal");
            }
            sb.AppendLine("POSTGUI_HALFILE = probe_basic_postgui.hal");
            sb.AppendLine();

            sb.AppendLine("[TRAJ]");
            sb.AppendLine($"AXES = {axesCount}");
            sb.AppendLine("SPINDLES = 1");
            sb.AppendLine($"COORDINATES = {coordinates}");
            sb.AppendLine("LINEAR_UNITS = mm");
            sb.AppendLine("ANGULAR_UNITS = degree");
            sb.AppendLine("DEFAULT_LINEAR_VELOCITY = 50");
            sb.AppendLine("MAX_LINEAR_VELOCITY = 125");
            sb.AppendLine();

            sb.AppendLine("[EMCIO]");
            sb.AppendLine("EMCIO = io");
            sb.AppendLine("CYCLE_TIME = 0.100");
            sb.AppendLine("TOOL_TABLE = tool_metric.tbl");
            sb.AppendLine("RANDOM_TOOLCHANGER = 0");
            sb.AppendLine();

            sb.AppendLine("[KINS]");
            sb.AppendLine($"JOINTS = {axesCount}");
            sb.AppendLine($"KINEMATICS = trivkins coordinates={geometry}");
            sb.AppendLine();

            sb.AppendLine("[SPINDLE]");
            sb.AppendLine("PGAIN_V = 0");
            sb.AppendLine("IGAIN_V = 0.01");
            sb.AppendLine("DGAIN_V = 0");
            sb.AppendLine("FF0_V = 1");
            sb.AppendLine("FF1_V = 0");
            sb.AppendLine("PGAIN_P = 100");
            sb.AppendLine("IGAIN_P = 1");
            sb.AppendLine("DGAIN_P = 0");
            sb.AppendLine("FF0_P = 0");
            sb.AppendLine("FF1_P = 1");
            sb.AppendLine();

            for (int i = 0; i < axesCount; i++)
            {
                var axis = config.Axes[i];
                string axisName = axis.AxisID.ToUpper();
                double pitch = axis.Pitch == 0 ? 5.0 : axis.Pitch;
                double scale = axis.PulsePerRev / pitch;

                sb.AppendLine($"# --- Axis {axisName} ---");
                sb.AppendLine($"[AXIS_{axisName}]");
                sb.AppendLine($"MIN_LIMIT = {axis.SoftLimitNeg}");
                sb.AppendLine($"MAX_LIMIT = {axis.SoftLimitPos}");
                sb.AppendLine($"MAX_VELOCITY = {axis.MaxVelocity}");
                sb.AppendLine($"MAX_ACCELERATION = {axis.MaxAcceleration}");
                sb.AppendLine();

                sb.AppendLine($"[JOINT_{i}]");
                sb.AppendLine("TYPE = LINEAR");
                sb.AppendLine("HOME = 0.0");
                sb.AppendLine($"MIN_LIMIT = {axis.SoftLimitNeg}");
                sb.AppendLine($"MAX_LIMIT = {axis.SoftLimitPos}");
                sb.AppendLine($"MAX_VELOCITY = {axis.MaxVelocity}");
                sb.AppendLine($"MAX_ACCELERATION = {axis.MaxAcceleration}");
                sb.AppendLine($"STEP_SCALE = {scale:0.0}");
                sb.AppendLine("FERROR = 50.0");
                sb.AppendLine("MIN_FERROR = 5.0");

                sb.AppendLine("P_GAIN = 1000");
                sb.AppendLine("I_GAIN = 0");
                sb.AppendLine("D_GAIN = 0");
                sb.AppendLine("FF0 = 0");
                sb.AppendLine("FF1 = 1.0");

                double searchVel = 0;
                double latchVel = 0;
                string useIndex = "NO";
                string ignoreLimits = "NO";

                switch (axis.HomingMode)
                {
                    case HomingMode.Immediate:
                        searchVel = 0; latchVel = 0; useIndex = "NO";
                        break;
                    case HomingMode.HomeSwitch:
                        searchVel = Math.Abs(axis.HomeSpeed) * axis.HomeDirection;
                        latchVel = Math.Abs(axis.HomeLatchSpeed) * axis.HomeDirection;
                        useIndex = axis.HomeUseIndex ? "YES" : "NO";
                        ignoreLimits = "YES";
                        break;
                    case HomingMode.LimitSwitch:
                        searchVel = Math.Abs(axis.HomeSpeed) * axis.HomeDirection;
                        latchVel = Math.Abs(axis.HomeLatchSpeed) * axis.HomeDirection;
                        useIndex = axis.HomeUseIndex ? "YES" : "NO";
                        ignoreLimits = "YES";
                        break;
                }

                sb.AppendLine($"HOME_OFFSET = {axis.HomeOffset}");
                sb.AppendLine($"HOME_SEARCH_VEL = {searchVel}");
                sb.AppendLine($"HOME_LATCH_VEL = {latchVel}");
                sb.AppendLine($"HOME_USE_INDEX = {useIndex}");
                sb.AppendLine($"HOME_IGNORE_LIMITS = {ignoreLimits}");
                sb.AppendLine($"HOME_SEQUENCE = {axis.HomeSequence}");
                sb.AppendLine();
            }
            return sb.ToString();
        }

        // ========================================================================================
        // 2. 生成 HAL (整合 IO Mappings 與標準訊號)
        // ========================================================================================
        private string GenerateHal(MachineConfig config)
        {
            var sb = new StringBuilder();
            int axesCount = config.Axes.Count;

            // [2026-03-05] 生成時間戳記
            sb.AppendLine($"# Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("loadrt [KINS]KINEMATICS");
            // [2026-03-09] num_dio=32：讓 motion module 建立 32 個 digital IO pin（供 ATC M64/M65/M66 使用）
            sb.AppendLine("loadrt [EMCMOT]EMCMOT servo_period_nsec=[EMCMOT]SERVO_PERIOD num_joints=[KINS]JOINTS num_dio=[EMCMOT]NUM_DIO");
            sb.AppendLine($"loadrt cia402 count={axesCount}");

            var sliceNames = string.Join(",", config.Axes.Select(a => $"slice_{a.AxisID}"));
            var personalities = string.Join(",", Enumerable.Repeat("32", axesCount));
            sb.AppendLine($"loadrt bitslice names={sliceNames} personality={personalities}");

            // 計算 NOT 元件總需求
            int axisNotCount = axesCount * 3;
            int ioInvertCount = config.Mappings
                .Where(m => m.Type == MapType.Input || m.Type == MapType.Output)
                .SelectMany(m => m.Pins)
                .Count(p => p.IsInverted);

            int totalNotCount = axisNotCount + ioInvertCount;

            if (totalNotCount > 0) sb.AppendLine($"loadrt not count={totalNotCount}");

            sb.AppendLine("loadusr -W lcec_conf ethercat-conf.xml");
            sb.AppendLine("loadrt lcec");
            sb.AppendLine();

            sb.AppendLine("addf lcec.read-all servo-thread");
            foreach (var axis in config.Axes) sb.AppendLine($"addf slice_{axis.AxisID} servo-thread");
            for (int i = 0; i < axesCount; i++) sb.AppendLine($"addf cia402.{i}.read-all servo-thread");

            if (totalNotCount > 0)
            {
                for (int k = 0; k < totalNotCount; k++) sb.AppendLine($"addf not.{k} servo-thread");
            }

            sb.AppendLine("addf motion-command-handler servo-thread");
            sb.AppendLine("addf motion-controller servo-thread");
            for (int i = 0; i < axesCount; i++) sb.AppendLine($"addf cia402.{i}.write-all servo-thread");
            sb.AppendLine("addf lcec.write-all servo-thread");
            sb.AppendLine();

            int currentNotIndex = 0;

            // =========================================================
            // A. 軸與馬達邏輯 (AXIS MAPPING)
            // =========================================================
            for (int i = 0; i < axesCount; i++)
            {
                var axis = config.Axes[i];
                string axisHalName = $"joint.{i}";

                // [2026-02-24] 修正：從 Mappings 動態取得 EtherCAT Slave Index，不再寫死 X→0, Y→2, Z→3
                // [2026-03-05] 修正：LogicalName 格式為 "X Axis"，需用 StartsWith 匹配 AxisID "X"
                string axName = axis.AxisID.ToUpper();
                var axisMapping = config.Mappings.FirstOrDefault(m =>
                    m.Type == MapType.Axis && m.LogicalName.StartsWith(axis.AxisID, StringComparison.OrdinalIgnoreCase));
                int sIdx;
                if (axisMapping != null)
                {
                    sIdx = axisMapping.PhysicalIndex;
                }
                else
                {
                    // 無映射時回退為 Joint Index（向後相容）
                    sIdx = axis.Index;
                    AlarmService.Instance.AddLog("WARN", $"No axis mapping found for {axis.AxisID}, fallback to slave index {sIdx}");
                }

                string sliceName = $"slice_{axis.AxisID}";

                // [2026-03-05] 重構：使用 ClassifyDevice() 統一設備類型判斷
                var map = config.Mappings.FirstOrDefault(m => m.PhysicalIndex == sIdx && m.Type == MapType.Axis)
                       ?? config.Mappings.FirstOrDefault(m => m.PhysicalIndex == sIdx);
                var deviceType = SlaveDeviceType.Unknown;
                // [2026-03-05] 傳入 DeviceCategory 優先用掃描結果判斷
                if (map != null) deviceType = ClassifyDevice(map.ExpectedVendorId, map.ExpectedProductCode, map.DeviceCategory);
                bool isServo = deviceType == SlaveDeviceType.Servo || deviceType == SlaveDeviceType.PulseGenerator;
                bool isPulseGen = deviceType == SlaveDeviceType.PulseGenerator;

                sb.AppendLine($"# --- Axis {axis.AxisID} (Slave {sIdx}) [Type: {(isServo ? "Servo" : "Stepper/OpenLoop")}] ---");

                sb.AppendLine($"net {axis.AxisID}-enable  {axisHalName}.amp-enable-out => cia402.{i}.enable");
                sb.AppendLine($"net {axis.AxisID}-control cia402.{i}.controlword => lcec.0.{sIdx}.control_word_J{sIdx}");
                sb.AppendLine($"net {axis.AxisID}-status  lcec.0.{sIdx}.status_word_J{sIdx} => cia402.{i}.statusword");

                sb.AppendLine($"setp cia402.{i}.csp-mode 1");

                // ★★★ [修正] 只有「不是」5621 才設定 Operation Mode ★★★
                if (isServo && !isPulseGen)
                {
                    sb.AppendLine($"setp lcec.0.{sIdx}.modes_of_operation_J{sIdx} 8");
                }

                sb.AppendLine($"setp cia402.{i}.pos-scale [JOINT_{i}]STEP_SCALE");

                sb.AppendLine($"net {axis.AxisID}-pos-cmd {axisHalName}.motor-pos-cmd => cia402.{i}.pos-cmd");
                sb.AppendLine($"net {axis.AxisID}-drv-target cia402.{i}.drv-target-position => lcec.0.{sIdx}.target_position_J{sIdx}");

                sb.AppendLine($"net {axis.AxisID}-pos-fb lcec.0.{sIdx}.position_actual_value_J{sIdx} => cia402.{i}.drv-actual-position");

                if (isServo && !isPulseGen)
                {
                    sb.AppendLine("# [Feedback] Real Encoder Feedback (Closed Loop)");
                    sb.AppendLine($"net {axis.AxisID}-pos-fb-final cia402.{i}.pos-fb => {axisHalName}.motor-pos-fb");
                }
                else
                {
                    sb.AppendLine("# [Feedback] Fake Feedback (Open Loop)");
                    sb.AppendLine($"net {axis.AxisID}-pos-cmd => {axisHalName}.motor-pos-fb");
                }

                sb.AppendLine($"net {axis.AxisID}-di-raw lcec.0.{sIdx}.digital_inputs_J{sIdx} => {sliceName}.in");

                // --- Homing & Limits Logic ---
                if (axis.HomingMode == HomingMode.Immediate)
                {
                    sb.AppendLine("# Homing: Immediate");
                }
                else if (axis.HomingMode == HomingMode.HomeSwitch)
                {
                    if (axis.HomeSwitchLogic != LimitLogic.NotUsed)
                    {
                        string rawHomeSig = $"{sliceName}.out-{axis.HomeDiIndex:00}";
                        if (axis.HomeSwitchLogic == LimitLogic.NC)
                        {
                            sb.AppendLine($"net {axis.AxisID}-home-raw {rawHomeSig} => not.{currentNotIndex}.in");
                            sb.AppendLine($"net {axis.AxisID}-home {axisHalName}.home-sw-in <= not.{currentNotIndex}.out");
                            currentNotIndex++;
                        }
                        else
                        {
                            sb.AppendLine($"net {axis.AxisID}-home {axisHalName}.home-sw-in <= {rawHomeSig}");
                        }
                    }
                }
                else if (axis.HomingMode == HomingMode.LimitSwitch)
                {
                    int targetDiIndex = (axis.HomeDirection > 0) ? axis.PosLimitDiIndex : axis.NegLimitDiIndex;
                    if (axis.LimitSwitchLogic != LimitLogic.NotUsed)
                    {
                        string rawSharedSig = $"{sliceName}.out-{targetDiIndex:00}";
                        if (axis.LimitSwitchLogic == LimitLogic.NC)
                        {
                            sb.AppendLine($"net {axis.AxisID}-home-shared-raw {rawSharedSig} => not.{currentNotIndex}.in");
                            sb.AppendLine($"net {axis.AxisID}-home {axisHalName}.home-sw-in <= not.{currentNotIndex}.out");
                            currentNotIndex++;
                        }
                        else
                        {
                            sb.AppendLine($"net {axis.AxisID}-home {axisHalName}.home-sw-in <= {rawSharedSig}");
                        }
                    }
                }

                if (axis.LimitSwitchLogic != LimitLogic.NotUsed)
                {
                    string rawNeg = $"{sliceName}.out-{axis.NegLimitDiIndex:00}";
                    if (axis.LimitSwitchLogic == LimitLogic.NC)
                    {
                        sb.AppendLine($"net {axis.AxisID}-neg-raw {rawNeg} => not.{currentNotIndex}.in");
                        sb.AppendLine($"net {axis.AxisID}-neg-lim {axisHalName}.neg-lim-sw-in <= not.{currentNotIndex}.out");
                        currentNotIndex++;
                    }
                    else
                    {
                        sb.AppendLine($"net {axis.AxisID}-neg-lim {axisHalName}.neg-lim-sw-in <= {rawNeg}");
                    }

                    string rawPos = $"{sliceName}.out-{axis.PosLimitDiIndex:00}";
                    if (axis.LimitSwitchLogic == LimitLogic.NC)
                    {
                        sb.AppendLine($"net {axis.AxisID}-pos-raw {rawPos} => not.{currentNotIndex}.in");
                        sb.AppendLine($"net {axis.AxisID}-pos-lim {axisHalName}.pos-lim-sw-in <= not.{currentNotIndex}.out");
                        currentNotIndex++;
                    }
                    else
                    {
                        sb.AppendLine($"net {axis.AxisID}-pos-lim {axisHalName}.pos-lim-sw-in <= {rawPos}");
                    }
                }
                sb.AppendLine();
            }

            // =========================================================
            // ★★★ B. 標準系統訊號來源 (Standard Signals) ★★★
            // =========================================================
            sb.AppendLine("# === STANDARD SIGNALS (Source) ===");
            sb.AppendLine("net coolant-flood iocontrol.0.coolant-flood");
            sb.AppendLine("net coolant-mist  iocontrol.0.coolant-mist");
            sb.AppendLine("net spindle-on    spindle.0.on");
            sb.AppendLine("net spindle-cw    spindle.0.forward");
            sb.AppendLine("net spindle-ccw   spindle.0.reverse");
            sb.AppendLine("net spindle-brake spindle.0.brake");
            sb.AppendLine();

            // =========================================================
            // C. 通用 IO 邏輯 (IN/OUT MAPPINGS)
            // =========================================================
            sb.AppendLine("# === GENERAL IO MAPPINGS ===");

            // [2026-03-09] 收集 ATC 佔用的 pin，避免 GENERAL IO 重複接線
            var atcReservedDi = new HashSet<int>();
            var atcReservedDo = new HashSet<int>();
            int atcIoSlave = -1;
            if (config.Atc.Type != AtcType.None && config.Atc.IoSlaveIndex >= 0)
            {
                atcIoSlave = config.Atc.IoSlaveIndex;
                atcReservedDo.Add(config.Atc.DoCarouselOut);
                atcReservedDo.Add(config.Atc.DoCarouselHome);
                atcReservedDo.Add(config.Atc.DoDrawbar);
                atcReservedDo.Add(config.Atc.DoAirBlow);
                atcReservedDo.Add(config.Atc.DoMotorFwd);
                atcReservedDo.Add(config.Atc.DoMotorRev);
                atcReservedDi.Add(config.Atc.DiCarouselHome);
                atcReservedDi.Add(config.Atc.DiCarouselOut);
                atcReservedDi.Add(config.Atc.DiDrawbarClamp);
                atcReservedDi.Add(config.Atc.DiDrawbarUnclamp);
                atcReservedDi.Add(config.Atc.DiRotationIndex);
            }

            // 處理 INPUT
            foreach (var map in config.Mappings.Where(m => m.Type == MapType.Input))
            {
                string devicePrefix = $"lcec.0.{map.PhysicalIndex}";
                sb.AppendLine($"# Input Group {map.ChannelIndex} (Slave {map.PhysicalIndex})");

                foreach (var pin in map.Pins)
                {
                    // [2026-03-09] 跳過已被 ATC DI 佔用的 pin（同 Slave 時）
                    if (map.PhysicalIndex == atcIoSlave && atcReservedDi.Contains(pin.Index))
                    {
                        sb.AppendLine($"# [ATC] skipped din-{pin.Index:00} (reserved for ATC DI)");
                        continue;
                    }

                    string hwPin = $"{devicePrefix}.din-{pin.Index:00}";
                    string signalName = string.IsNullOrWhiteSpace(pin.Function)
                        ? $"input-G{map.ChannelIndex}-{pin.Index:00}"
                        : CleanSignalName(pin.Function);

                    // [2026-03-05] 模擬模式：跳過 probe-in 整條接線（由 sim_probe.hal 建立）
                    if (signalName == "probe-in" && IsProbeSimulation)
                    {
                        sb.AppendLine($"# [SIM] skipped: net {signalName} {hwPin} (handled by sim_probe.hal)");
                        continue;
                    }

                    if (pin.IsInverted)
                    {
                        sb.AppendLine($"net raw-{signalName} {hwPin} => not.{currentNotIndex}.in");
                        sb.AppendLine($"net {signalName} not.{currentNotIndex}.out");
                        currentNotIndex++;
                    }
                    else
                    {
                        sb.AppendLine($"net {signalName} {hwPin}");
                    }

                    // [2026-03-05] 實機模式：probe-in → motion.probe-input
                    if (signalName == "probe-in")
                    {
                        sb.AppendLine($"net {signalName} => motion.probe-input");
                    }
                }
                sb.AppendLine();
            }

            // 處理 OUTPUT
            foreach (var map in config.Mappings.Where(m => m.Type == MapType.Output))
            {
                string devicePrefix = $"lcec.0.{map.PhysicalIndex}";
                sb.AppendLine($"# Output Group {map.ChannelIndex} (Slave {map.PhysicalIndex})");

                foreach (var pin in map.Pins)
                {
                    // [2026-03-09] 跳過已被 ATC DO 佔用的 pin（同 Slave 時）
                    if (map.PhysicalIndex == atcIoSlave && atcReservedDo.Contains(pin.Index))
                    {
                        sb.AppendLine($"# [ATC] skipped dout-{pin.Index:00} (reserved for ATC DO)");
                        continue;
                    }

                    string hwPin = $"{devicePrefix}.dout-{pin.Index:00}";
                    string signalName = string.IsNullOrWhiteSpace(pin.Function)
                        ? $"output-G{map.ChannelIndex}-{pin.Index:00}"
                        : CleanSignalName(pin.Function);

                    if (pin.IsInverted)
                    {
                        sb.AppendLine($"net {signalName} => not.{currentNotIndex}.in");
                        sb.AppendLine($"net inv-{signalName} not.{currentNotIndex}.out => {hwPin}");
                        currentNotIndex++;
                    }
                    else
                    {
                        sb.AppendLine($"net {signalName} => {hwPin}");
                    }
                }
                sb.AppendLine();
            }

            // =========================================================
            // [2026-03-09] D. ATC IO 接線 (motion.digital-out/in ↔ EtherCAT IO)
            //   - 先檢查 ATC pin 與 GENERAL IO 是否衝突
            //   - 衝突 → 寫警告註解、跳過整段 ATC IO，不輸出
            // =========================================================
            if (config.Atc.Type != AtcType.None && config.Atc.IoSlaveIndex >= 0)
            {
                int ioSlave = config.Atc.IoSlaveIndex;

                // [2026-03-09] 收集 GENERAL IO 已佔用的 pin index（同 Slave、且有實際功能的 pin 才算）
                // 排除空白和預設佔位名（如 "Pin0"~"Pin31"）
                var generalDoPins = new HashSet<int>();
                var generalDiPins = new HashSet<int>();
                foreach (var map in config.Mappings.Where(m => m.Type == MapType.Output && m.PhysicalIndex == ioSlave))
                    foreach (var pin in map.Pins.Where(p => IsRealFunction(p.Function)))
                        generalDoPins.Add(pin.Index);
                foreach (var map in config.Mappings.Where(m => m.Type == MapType.Input && m.PhysicalIndex == ioSlave))
                    foreach (var pin in map.Pins.Where(p => IsRealFunction(p.Function)))
                        generalDiPins.Add(pin.Index);

                var doMappings = new (int PWord, string Name)[]
                {
                    (config.Atc.DoCarouselOut, "carousel-out"),
                    (config.Atc.DoCarouselHome, "carousel-home"),
                    (config.Atc.DoDrawbar, "drawbar"),
                    (config.Atc.DoAirBlow, "air-blow"),
                    (config.Atc.DoMotorFwd, "motor-fwd"),
                    (config.Atc.DoMotorRev, "motor-rev"),
                };
                var diMappings = new (int PWord, string Name)[]
                {
                    (config.Atc.DiCarouselHome, "carousel-home-in"),
                    (config.Atc.DiCarouselOut, "carousel-out-in"),
                    (config.Atc.DiDrawbarClamp, "drawbar-clamp-in"),
                    (config.Atc.DiDrawbarUnclamp, "drawbar-unclamp-in"),
                    (config.Atc.DiRotationIndex, "rotation-index-in"),
                };

                // [2026-03-09] 衝突檢查：ATC DO/DI 是否與 GENERAL IO 用到相同 pin
                var conflicts = new List<string>();
                foreach (var (pWord, name) in doMappings)
                    if (generalDoPins.Contains(pWord))
                        conflicts.Add($"DO pin {pWord} (atc-{name}) conflicts with General IO output");
                foreach (var (pWord, name) in diMappings)
                    if (generalDiPins.Contains(pWord))
                        conflicts.Add($"DI pin {pWord} (atc-{name}) conflicts with General IO input");

                if (conflicts.Count > 0)
                {
                    // [2026-03-09] 有衝突：寫警告註解，不輸出 ATC IO 接線
                    sb.AppendLine("# === ATC IO WIRING — SKIPPED (PIN CONFLICT) ===");
                    sb.AppendLine($"# WARNING: ATC IO Slave {ioSlave} has {conflicts.Count} pin conflict(s):");
                    foreach (var c in conflicts)
                        sb.AppendLine($"#   - {c}");
                    sb.AppendLine("# Please reassign ATC IO pins in Settings → ATC IO to avoid overlap.");
                    sb.AppendLine();
                    // [2026-03-09] 同步記錄到 AlarmService 供 UI 跑馬燈顯示
                    AlarmService.Instance.AddLog("ERROR",
                        $"ATC IO 衝突：Slave {ioSlave} 有 {conflicts.Count} 個 pin 與通用 IO 重複，HAL 未輸出 ATC 接線。請至 ATC IO 設定調整 pin 編號。");
                }
                else
                {
                    // [2026-03-09] 無衝突：正常輸出 ATC IO 接線
                    sb.AppendLine("# === ATC IO WIRING ===");
                    foreach (var (pWord, name) in doMappings)
                        sb.AppendLine($"net atc-do-{name} motion.digital-out-{pWord:00} => lcec.0.{ioSlave}.dout-{pWord:00}");
                    foreach (var (pWord, name) in diMappings)
                        sb.AppendLine($"net atc-di-{name} lcec.0.{ioSlave}.din-{pWord:00} => motion.digital-in-{pWord:00}");
                    sb.AppendLine();
                }
            }

            sb.AppendLine();
            sb.AppendLine("# --- SAFETY BYPASS (FORCE CONNECTION) ---");
            sb.AppendLine("unlinkp iocontrol.0.emc-enable-in");
            sb.AppendLine("net logic-enable iocontrol.0.user-enable-out => iocontrol.0.emc-enable-in");

            return sb.ToString();
        }

        // ========================================================================================
        // 3. 生成 XML (EtherCAT Topology - 修正混合模組與脈波模組)
        // ========================================================================================
        private string GenerateXml(MachineConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            // [2026-03-05] 生成時間戳記
            sb.AppendLine($"<!-- Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss} -->");
            sb.AppendLine("<masters>");
            sb.AppendLine($"  <master idx=\"0\" appTimePeriod=\"1000000\" refClockSyncCycles=\"1000\">");

            int maxSlaveIndex = 0;
            if (config.Mappings.Any())
                maxSlaveIndex = config.Mappings.Max(m => m.PhysicalIndex);
            if (maxSlaveIndex < 1) maxSlaveIndex = 1;

            for (int i = 0; i <= maxSlaveIndex; i++)
            {
                // 1. 找出這個 Slave Index 所有相關的設定 (可能同時有 IN 和 OUT)
                var slaveMappings = config.Mappings.Where(m => m.PhysicalIndex == i).ToList();

                // [2026-03-05] 修正：優先取 Axis mapping，確保 isServo 判斷正確（避免取到 IO mapping）
                var mainMap = slaveMappings.FirstOrDefault(m => m.Type == MapType.Axis)
                           ?? slaveMappings.FirstOrDefault();

                if (mainMap != null)
                {
                    // [2026-03-05] 重構：使用 ClassifyDevice() 統一設備類型判斷（傳入 DeviceCategory 優先）
                    var deviceType = ClassifyDevice(mainMap.ExpectedVendorId, mainMap.ExpectedProductCode, mainMap.DeviceCategory);

                    // [2026-03-05] 擴充：依設備類型 switch 生成對應 XML
                    switch (deviceType)
                    {
                        case SlaveDeviceType.Coupler:
                            // Coupler：不配置 PDO
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"false\"/>");
                            break;

                        case SlaveDeviceType.Servo:
                        case SlaveDeviceType.PulseGenerator:
                        {
                            bool isPulseGen = deviceType == SlaveDeviceType.PulseGenerator;
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x300\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");

                            // CiA 402 Output PDOs
                            sb.AppendLine("      <syncManager idx=\"2\" dir=\"out\">");
                            sb.AppendLine("        <pdo idx=\"1600\">");
                            sb.AppendLine($"          <pdoEntry idx=\"6040\" subIdx=\"00\" bitLen=\"16\" halPin=\"control_word_J{i}\" halType=\"u32\"/>");
                            sb.AppendLine($"          <pdoEntry idx=\"607a\" subIdx=\"00\" bitLen=\"32\" halPin=\"target_position_J{i}\" halType=\"s32\"/>");
                            if (!isPulseGen)
                                sb.AppendLine($"          <pdoEntry idx=\"6060\" subIdx=\"00\" bitLen=\"8\" halPin=\"modes_of_operation_J{i}\" halType=\"s32\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");

                            // CiA 402 Input PDOs
                            sb.AppendLine("      <syncManager idx=\"3\" dir=\"in\">");
                            sb.AppendLine("        <pdo idx=\"1a00\">");
                            sb.AppendLine($"          <pdoEntry idx=\"6041\" subIdx=\"00\" bitLen=\"16\" halPin=\"status_word_J{i}\" halType=\"u32\"/>");
                            sb.AppendLine($"          <pdoEntry idx=\"6064\" subIdx=\"00\" bitLen=\"32\" halPin=\"position_actual_value_J{i}\" halType=\"s32\"/>");
                            if (!isPulseGen)
                                sb.AppendLine($"          <pdoEntry idx=\"6061\" subIdx=\"00\" bitLen=\"8\" halPin=\"modes_of_operation_display_J{i}\" halType=\"s32\"/>");
                            sb.AppendLine($"          <pdoEntry idx=\"60fd\" subIdx=\"00\" bitLen=\"32\" halPin=\"digital_inputs_J{i}\" halType=\"u32\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        case SlaveDeviceType.IoModule:
                        {
                            // DI+DO 混合 IO（台達 R2-EC0902）— Free Run + 32x din + 32x dout
                            bool hasInput = slaveMappings.Any(m => m.Type == MapType.Input);
                            bool hasOutput = slaveMappings.Any(m => m.Type == MapType.Output);
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x0\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");

                            // Output 32 bits
                            if (hasOutput || true) // IoModule 永遠生成 IO
                            {
                                sb.AppendLine("      <syncManager idx=\"2\" dir=\"out\">");
                                sb.AppendLine("        <pdo idx=\"1600\">");
                                for (int k = 0; k < 32; k++)
                                    sb.AppendLine($"          <pdoEntry idx=\"0x7000\" subIdx=\"0x{k + 1:X2}\" bitLen=\"1\" halPin=\"dout-{k:00}\" halType=\"bit\"/>");
                                sb.AppendLine("        </pdo>");
                                sb.AppendLine("      </syncManager>");
                            }

                            // Input 32 bits
                            if (hasInput || true) // IoModule 永遠生成 IO
                            {
                                sb.AppendLine("      <syncManager idx=\"3\" dir=\"in\">");
                                sb.AppendLine("        <pdo idx=\"1a00\">");
                                for (int k = 0; k < 32; k++)
                                    sb.AppendLine($"          <pdoEntry idx=\"0x6000\" subIdx=\"0x{k + 1:X2}\" bitLen=\"1\" halPin=\"din-{k:00}\" halType=\"bit\"/>");
                                sb.AppendLine("        </pdo>");
                                sb.AppendLine("      </syncManager>");
                            }
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        case SlaveDeviceType.DigitalInput:
                        {
                            // DI-only — Free Run + 32x din
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x0\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");
                            sb.AppendLine("      <syncManager idx=\"3\" dir=\"in\">");
                            sb.AppendLine("        <pdo idx=\"1a00\">");
                            for (int k = 0; k < 32; k++)
                                sb.AppendLine($"          <pdoEntry idx=\"0x6000\" subIdx=\"0x{k + 1:X2}\" bitLen=\"1\" halPin=\"din-{k:00}\" halType=\"bit\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        case SlaveDeviceType.DigitalOutput:
                        {
                            // DO-only — Free Run + 32x dout
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x0\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");
                            sb.AppendLine("      <syncManager idx=\"2\" dir=\"out\">");
                            sb.AppendLine("        <pdo idx=\"1600\">");
                            for (int k = 0; k < 32; k++)
                                sb.AppendLine($"          <pdoEntry idx=\"0x7000\" subIdx=\"0x{k + 1:X2}\" bitLen=\"1\" halPin=\"dout-{k:00}\" halType=\"bit\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        case SlaveDeviceType.Mpg:
                        {
                            // MPG 手輪 — Free Run + mpg-buttons (6000:01) + mpg-counts (6064:00)
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x0\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");
                            sb.AppendLine("      <syncManager idx=\"3\" dir=\"in\">");
                            sb.AppendLine("        <pdo idx=\"1a00\">");
                            sb.AppendLine("          <pdoEntry idx=\"6000\" subIdx=\"01\" bitLen=\"16\" halPin=\"mpg-buttons\" halType=\"u32\"/>");
                            sb.AppendLine("          <pdoEntry idx=\"6064\" subIdx=\"00\" bitLen=\"32\" halPin=\"mpg-counts\" halType=\"s32\"/>");
                            sb.AppendLine("        </pdo>");
                            sb.AppendLine("      </syncManager>");
                            sb.AppendLine("    </slave>");
                            break;
                        }

                        default: // Unknown
                        {
                            // 安全預設：DC Sync 0x300，無 PDO
                            sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"{mainMap.ExpectedVendorId}\" pid=\"{mainMap.ExpectedProductCode}\" configPdos=\"true\">");
                            sb.AppendLine("      <dcConf assignActivate=\"0x300\" sync0Cycle=\"*1\" sync0Shift=\"0\"/>");
                            sb.AppendLine("    </slave>");
                            break;
                        }
                    }
                }
                else
                {
                    // Empty Slave
                    sb.AppendLine($"    <slave idx=\"{i}\" type=\"generic\" vid=\"000001dd\" pid=\"00005500\" configPdos=\"false\"/>");
                }
            }

            sb.AppendLine("  </master>");
            sb.AppendLine("</masters>");
            return sb.ToString();
        }

        // ========================================================================================
        // [2026-03-09] 生成 ATC NGC 巨集（依 AtcType 動態生成 4 個類型相關檔案）
        // 回傳 Dictionary<檔名, 內容>：m21.ngc / m22.ngc / toolchange.ngc / m13.ngc
        // ========================================================================================
        private Dictionary<string, string> GenerateAtcNgc(MachineConfig config)
        {
            var ngcFiles = new Dictionary<string, string>();

            if (config.Atc.Type == AtcType.None) return ngcFiles;

            // 依 AtcType 選擇 PB Widget 名稱
            string widgetName = config.Atc.Type == AtcType.Umbrella ? "dynatc" : "rackatc";
            int pockets = config.Atc.ToolCount;

            // --- toolchange.ngc（M6 主程式）---
            ngcFiles["toolchange.ngc"] = GenerateToolchangeNgc(config, widgetName, pockets);

            // --- m13.ngc（刀庫歸零/初始化）---
            ngcFiles["m13.ngc"] = GenerateM13Ngc(widgetName, pockets);

            // --- m21.ngc（存刀：spindle → rack/carousel）---
            if (config.Atc.Type == AtcType.Turret)
                ngcFiles["m21.ngc"] = GenerateM21Rack();
            else
                ngcFiles["m21.ngc"] = GenerateM21Carousel();

            // --- m22.ngc（取刀：rack/carousel → spindle）---
            if (config.Atc.Type == AtcType.Turret)
                ngcFiles["m22.ngc"] = GenerateM22Rack();
            else
                ngcFiles["m22.ngc"] = GenerateM22Carousel();

            return ngcFiles;
        }

        // --- toolchange.ngc ---
        private string GenerateToolchangeNgc(MachineConfig config, string widgetName, int pockets)
        {
            // [2026-03-09] M6 REMAP 主程式：Rack/Carousel 共用邏輯，僅 Widget 名稱不同
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<toolchange> sub

o100 if [#<_task> EQ 0]
    (DEBUG, Task is null)
    o<toolchange> return [999]
o100 endif

#<number_of_pockets> = {pockets}
o101 if [EXISTS[#<_ini[atc]pockets>]]
    #<number_of_pockets> = #<_ini[atc]pockets>
o101 endif

#<atc_z_tool_change_height> = #3981
#<atc_z_tool_clearance_height> = #3982

#100 = #<selected_tool>
#110 = #<tool_in_spindle>
#120 = #<selected_pocket>
#121 = #<current_pocket>

o110 if [#<selected_tool> EQ #<tool_in_spindle>]
    (PRINT, Requested tool already in spindle)
    o<toolchange> endsub [1]
    M2
o110 endif

#<next_pocket> = 0
#<open_pocket> = 0
#130 = #<number_of_pockets>

o130 do
    o161 if [#[4000 + #130] EQ #<selected_tool>]
        #<next_pocket> = #130
    o161 endif
    o162 if [#[4000 + #130] EQ 0]
        #<open_pocket> = #130
    o162 endif
    #130 = [#130 - 1]
o130 while [#130 GT 0]

o140 if [#<next_pocket> EQ 0]
    (abort, Tool T%d#<selected_tool> not found in rack)
o140 endif

o150 if [#<tool_in_spindle> GT 0]
    o151 if [#<open_pocket> EQ 0]
        (abort, rack is full, cant store tool T#<tool_in_spindle> in rack)
    o151 endif
    o<m21> call [#<open_pocket>]
    (DEBUG, EVAL[vcp.getWidget{{""{widgetName}""}}.store_tool{{#<open_pocket>, #<tool_in_spindle>}}])
    #140 = #<open_pocket>
    #[4000 + #140] = #<tool_in_spindle>
    #3991 = 0
    M61 Q0
    G49
o150 endif

o160 if [#<selected_tool> GT 0]
    o<m22> call [#<next_pocket>]
    (DEBUG, EVAL[vcp.getWidget{{""{widgetName}""}}.store_tool{{#<next_pocket>, 0}}])
    #150 = #<next_pocket>
    #[4000 + #150] = 0
    #3991 = #<selected_tool>
o160 else
    M25
o160 endif

M61 Q#<selected_tool>

o170 if [1 EQ 1]
    G43 H#<selected_tool>
o170 endif

o<program_coolant> call

o<toolchange> endsub [1]

M2
";
        }

        // --- m13.ngc ---
        private string GenerateM13Ngc(string widgetName, int pockets)
        {
            // [2026-03-09] 刀庫歸零/同步：讀取持久變數 #4001~#40xx 並更新 PB Widget
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<m13> sub

(PRINT, o<m13>)

#<number_of_pockets> = {pockets}
o110 if [EXISTS[#<_ini[atc]pockets>]]
    #<number_of_pockets> = #<_ini[atc]pockets>
o110 endif

#1 = 0

o120 while [#1 LT #<number_of_pockets>]
    #1 = [#1+1]
    #2 = #[4000+#1]
    (DEBUG, EVAL[vcp.getWidget{{""{widgetName}""}}.store_tool{{#1, #2}}])
o120 endwhile

M61 Q#3991 G43 H#3991

(PRINT, o<m13> endsub)
o<m13> endsub [1]

M2
";
        }

        // --- m21.ngc Rack 版（排刀式存刀）---
        private string GenerateM21Rack()
        {
            // [2026-03-09] Rack 版：計算 XY 座標 → 移動主軸 → M19 → 滑入刀座 → M24 鬆刀 → Z 退
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<m21> sub

#<target_pocket> = #1

#<rack_id>                = #3979
#<rack_traverse_speed>    = #3980
#<rack_z_load_height>     = #3981
#<rack_safe_z_height>     = #3982
#<rack_pocket_1_x>        = #3983
#<rack_pocket_1_y>        = #3984
#<rack_pocket_2_x>        = #3985
#<rack_pocket_2_y>        = #3986
#<pocket_1_x_clearance>   = #3987
#<pocket_1_y_clearance>   = #3988

#<dx> = [#<rack_pocket_2_x> - #<rack_pocket_1_x>]
#<dy> = [#<rack_pocket_2_y> - #<rack_pocket_1_y>]
#<pocket_index> = [#<target_pocket> - 1]
#<pocket_x> = [#<rack_pocket_1_x> + #<pocket_index> * #<dx>]
#<pocket_y> = [#<rack_pocket_1_y> + #<pocket_index> * #<dy>]

#<clearance_x> = #<pocket_x>
#<clearance_y> = #<pocket_y>
#<store_axis> = 0
#<store_sign> = 1

o100 if [#<rack_id> EQ 1]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<store_axis> = 1
    #<store_sign> = -1
o100 elseif [#<rack_id> EQ 2]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<store_axis> = 1
    #<store_sign> = 1
o100 elseif [#<rack_id> EQ 3]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<store_axis> = 1
    #<store_sign> = -1
o100 elseif [#<rack_id> EQ 4]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<store_axis> = 1
    #<store_sign> = 1
o100 elseif [#<rack_id> EQ 5]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<store_axis> = 2
    #<store_sign> = -1
o100 elseif [#<rack_id> EQ 6]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<store_axis> = 2
    #<store_sign> = 1
o100 elseif [#<rack_id> EQ 7]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<store_axis> = 2
    #<store_sign> = -1
o100 elseif [#<rack_id> EQ 8]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<store_axis> = 2
    #<store_sign> = 1
o100 else
    (PRINT, Error: Invalid rack_id!)
    o<m21> return
o100 endif

G90
G0 G53 Z[#<rack_safe_z_height>]
G0 G53 X[#<clearance_x>] Y[#<clearance_y>]
G1 G53 F[#<rack_traverse_speed>] Z[#<rack_z_load_height>]
M19
G4 P1

o200 if [#<store_axis> EQ 1]
    G1 G53 F[#<rack_traverse_speed>] X[#<pocket_x>]
o200 else
    G1 G53 F[#<rack_traverse_speed>] Y[#<pocket_y>]
o200 endif

M24
G0 G53 Z[#<rack_safe_z_height>]

o<m21> endsub

M2
";
        }

        // --- m21.ngc Carousel 版（斗笠式存刀）---
        private string GenerateM21Carousel()
        {
            // [2026-03-09] Carousel 版：Z 淨空 → M10 旋轉 → M19 → extendatc → Z 下降 → M24 鬆刀 → Z 退 → retractatc
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<m21> sub

#<target_pocket> = #1

#<atc_z_tool_change_height> = #3981
#<atc_z_tool_clearance_height> = #3982

o100 if [EXISTS[#<_ini[atc]z_tool_change_height>]]
    #<atc_z_tool_change_height> = #<_ini[atc]z_tool_change_height>
o100 endif
o110 if [EXISTS[#<_ini[atc]z_tool_clearance_height>]]
    #<atc_z_tool_clearance_height> = #<_ini[atc]z_tool_clearance_height>
o110 endif

G90
; 1. Move Z to clearance height
G0 G53 Z[#<atc_z_tool_clearance_height>]

; 2. Rotate carousel to target pocket
M10 P[#<target_pocket>]

; 3. Orient spindle
M19
G4 P1

; 4. Extend carousel out
o<extendatc> call

; 5. Lower Z to tool change height
G1 G53 F500 Z[#<atc_z_tool_change_height>]

; 6. Release tool (unclamp drawbar)
M24
G4 P0.5

; 7. Raise Z to clearance height
G0 G53 Z[#<atc_z_tool_clearance_height>]

; 8. Retract carousel
o<retractatc> call

o<m21> endsub

M2
";
        }

        // --- m22.ngc Rack 版（排刀式取刀）---
        private string GenerateM22Rack()
        {
            // [2026-03-09] Rack 版：移動主軸到 XY → M19 → M24 → Z 下降 → M25 夾刀 → 滑出
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<m22> sub

#<target_pocket> = #1

#<rack_id>                = #3979
#<rack_traverse_speed>    = #3980
#<rack_z_load_height>     = #3981
#<rack_safe_z_height>     = #3982
#<rack_pocket_1_x>        = #3983
#<rack_pocket_1_y>        = #3984
#<rack_pocket_2_x>        = #3985
#<rack_pocket_2_y>        = #3986
#<pocket_1_x_clearance>   = #3987
#<pocket_1_y_clearance>   = #3988

#<dx> = [#<rack_pocket_2_x> - #<rack_pocket_1_x>]
#<dy> = [#<rack_pocket_2_y> - #<rack_pocket_1_y>]
#<pocket_index> = [#<target_pocket> - 1]
#<pocket_x> = [#<rack_pocket_1_x> + #<pocket_index> * #<dx>]
#<pocket_y> = [#<rack_pocket_1_y> + #<pocket_index> * #<dy>]

#<clearance_x> = #<pocket_x>
#<clearance_y> = #<pocket_y>
#<retrieve_axis> = 0
#<retrieve_sign> = 1

o100 if [#<rack_id> EQ 1]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<retrieve_axis> = 1
    #<retrieve_sign> = 1
o100 elseif [#<rack_id> EQ 2]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<retrieve_axis> = 1
    #<retrieve_sign> = -1
o100 elseif [#<rack_id> EQ 3]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<retrieve_axis> = 1
    #<retrieve_sign> = 1
o100 elseif [#<rack_id> EQ 4]
    #<clearance_x> = #<pocket_1_x_clearance>
    #<retrieve_axis> = 1
    #<retrieve_sign> = -1
o100 elseif [#<rack_id> EQ 5]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<retrieve_axis> = 2
    #<retrieve_sign> = 1
o100 elseif [#<rack_id> EQ 6]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<retrieve_axis> = 2
    #<retrieve_sign> = -1
o100 elseif [#<rack_id> EQ 7]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<retrieve_axis> = 2
    #<retrieve_sign> = 1
o100 elseif [#<rack_id> EQ 8]
    #<clearance_y> = #<pocket_1_y_clearance>
    #<retrieve_axis> = 2
    #<retrieve_sign> = -1
o100 else
    (PRINT, Error: Invalid rack_id!)
    o<m22> return
o100 endif

G90
G0 G53 Z[#<rack_safe_z_height>]
G0 G53 X[#<pocket_x>] Y[#<pocket_y>]
M19
M24
G1 G53 F[#<rack_traverse_speed>] Z[#<rack_z_load_height>]
M25

o200 if [#<retrieve_axis> EQ 1]
    G1 G53 F[#<rack_traverse_speed>] X[#<clearance_x>]
o200 else
    G1 G53 F[#<rack_traverse_speed>] Y[#<clearance_y>]
o200 endif

G0 G53 Z[#<rack_safe_z_height>]

o<m22> endsub

M2
";
        }

        // --- m22.ngc Carousel 版（斗笠式取刀）---
        private string GenerateM22Carousel()
        {
            // [2026-03-09] Carousel 版：Z 淨空 → M10 旋轉 → M19 → extendatc → M24 鬆夾 → Z 下降 → M25 夾刀 → Z 退 → retractatc
            return $@"(Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss})
o<m22> sub

#<target_pocket> = #1

#<atc_z_tool_change_height> = #3981
#<atc_z_tool_clearance_height> = #3982

o100 if [EXISTS[#<_ini[atc]z_tool_change_height>]]
    #<atc_z_tool_change_height> = #<_ini[atc]z_tool_change_height>
o100 endif
o110 if [EXISTS[#<_ini[atc]z_tool_clearance_height>]]
    #<atc_z_tool_clearance_height> = #<_ini[atc]z_tool_clearance_height>
o110 endif

G90
; 1. Move Z to clearance height
G0 G53 Z[#<atc_z_tool_clearance_height>]

; 2. Rotate carousel to target pocket
M10 P[#<target_pocket>]

; 3. Orient spindle
M19
G4 P1

; 4. Extend carousel out
o<extendatc> call

; 5. Unclamp drawbar to receive tool
M24

; 6. Lower Z to tool change height
G1 G53 F500 Z[#<atc_z_tool_change_height>]

; 7. Clamp tool in spindle
M25
G4 P0.5

; 8. Raise Z to clearance height
G0 G53 Z[#<atc_z_tool_clearance_height>]

; 9. Retract carousel
o<retractatc> call

o<m22> endsub

M2
";
        }

        private string GeneratePostGuiHal(MachineConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Generated by CncController - PostGUI");
            sb.AppendLine("# 這裡只負責將 HAL 訊號連接到 Probe Basic 介面");
            sb.AppendLine("# ★★★ 絕對不要在這裡 loadrt not/bitslice，因為主 HAL 已經載入了 ★★★");
            sb.AppendLine();
            return sb.ToString();
        }

        // [2026-03-05] 重構：ClassifyDevice() 取代 IsServoDrive()，統一設備類型判斷邏輯
        // [2026-03-05] 新增 deviceCategory 參數：優先用後端掃描結果，fallback VID/PID 比對
        private static SlaveDeviceType ClassifyDevice(string vidStr, string pidStr, string deviceCategory = "")
        {
            // 優先用後端掃描結果的 Category（新設定檔已儲存）
            if (!string.IsNullOrEmpty(deviceCategory))
            {
                return deviceCategory switch
                {
                    Models.DeviceCategory.Servo    => SlaveDeviceType.Servo,
                    Models.DeviceCategory.PulseGen => SlaveDeviceType.PulseGenerator,
                    Models.DeviceCategory.DiDo     => SlaveDeviceType.IoModule,
                    Models.DeviceCategory.DigIn    => SlaveDeviceType.DigitalInput,
                    Models.DeviceCategory.DigOut   => SlaveDeviceType.DigitalOutput,
                    Models.DeviceCategory.Mpg      => SlaveDeviceType.Mpg,
                    Models.DeviceCategory.Coupler  => SlaveDeviceType.Coupler,
                    _                              => SlaveDeviceType.Unknown,
                };
            }

            // Fallback：用 VID/PID 字串比對（手動建立映射或舊設定檔相容）
            if (string.IsNullOrEmpty(pidStr)) return SlaveDeviceType.Unknown;
            string p = pidStr.ToLower().Trim().Replace("0x", "");
            string v = vidStr?.ToLower().Trim().Replace("0x", "") ?? "";

            // 匯川伺服
            if (p.Contains("c010d") || p.Contains("916")) return SlaveDeviceType.Servo;

            // 台達系列
            if (v.Contains("1dd"))
            {
                if (p.Contains("902"))  return SlaveDeviceType.IoModule;       // R2-EC0902
                if (p.Contains("5621")) return SlaveDeviceType.PulseGenerator; // 5621
                return SlaveDeviceType.Servo;                                   // 6080 等
            }

            return SlaveDeviceType.Unknown;
        }

        // [2026-03-09] 判斷 pin Function 是否為真正的功能（非空白、非預設佔位名 "Pin0"~"Pin31"）
        private static bool IsRealFunction(string function)
        {
            if (string.IsNullOrWhiteSpace(function)) return false;
            // [2026-03-09] 預設佔位名格式："Pin0", "Pin 0", "Pin 10", "Pin31" 等（不區分大小寫，中間可有空格）
            if (System.Text.RegularExpressions.Regex.IsMatch(function.Trim(), @"^Pin\s*\d+$", System.Text.RegularExpressions.RegexOptions.IgnoreCase))
                return false;
            return true;
        }

        private string CleanSignalName(string name)
        {
            if (string.IsNullOrEmpty(name)) return "unknown";
            char[] arr = name.ToCharArray();
            arr = Array.FindAll(arr, (c => (char.IsLetterOrDigit(c) || c == '_' || c == '-')));
            return new string(arr).Trim().Replace(" ", "-");
        }

        // ========================================================================================
        // [2026-03-05] 生成 sim_probe.hal — 探針模擬接線（3 軸 comp + or2 串聯）
        // RT 模組（comp/or2）由 simulated_home_probe_basic.hal 集中載入
        // ========================================================================================
        // [2026-03-05] 生成自包含的 sim_probe.hal（loadrt + addf + 接線全部在此）
        // 需要 config 判斷位置回饋訊號名稱（servo → {AxisID}-pos-fb-final, pulseGen → {AxisID}-pos-cmd）
        // [2026-03-06] 簡化探針模擬 HAL：移除 near/or2 自動觸發架構，改用手動 signal
        //              前端按鈕透過 /v2/hal/setp 設定 probe-in = 1/0，使用者自行控制觸發時機
        private string GenerateSimProbeHal(MachineConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# Generated by CncController — {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("# Probe Simulation HAL (manual trigger mode)");
            sb.AppendLine("# User toggles probe-in signal via frontend button");
            sb.AppendLine();
            sb.AppendLine("# 建立 probe-in signal 並連接 motion.probe-input（預設 0 = 未觸發）");
            sb.AppendLine("net probe-in motion.probe-input");
            sb.AppendLine("sets probe-in 0");
            return sb.ToString();
        }
    }
}