<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Components\JogConfig.xaml.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Views\Components\JogConfig.xaml.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
  </ItemGroup>

</Project>
